2D AFPM example
Severson-Group/eMach-matlab pull request #101
Opened 2019-05-19 23:26 UTC by ngadiyar93

This PR implements a 2D AFPM Example which:
1) Draws the AFPM equivalent 2D Model
2) Assigns Boundary Condition
3) Solves the model in MagNet (Transient)
4) Extracts results from MagNet into Matlab
5) Plots the results

2019-05-20 03:28 UTC, ngadiyar93 commented
This PR is ready for review.

2019-05-20 18:24 UTC, elsevers requested changes
Looks good! Please make these changes and then we can merge.

2019-05-20 18:24 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_createEvenPeriodicBoundaryCondition.m
> +function [boundary] = mn_d_createEvenPeriodicBoundaryCondition(mn, problemID, surfacesFace, Face , x, y, z, name )
`mn_d_createEvenPeriodicBoundaryCondition()` should be a porcelain function -- please move it over to the porcelain location.

2019-05-20 18:24 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_createEvenPeriodicBoundaryCondition.m
> +cmdstring = sprintf('call getDocument.createBoundaryCondition(nmArray,"%s")', name);
Create a plumbing function for `createBoundaryCondition`

2019-05-20 18:24 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_createEvenPeriodicBoundaryCondition.m
> +invoke(mn, 'processcommand', sprintf('call getDocument.setEvenPeriodic("%s",Null,Null,Null,Null,ShiftVector,Null)',name));
Create a plumbing function for `setEvenPeriodic`

2019-05-20 18:24 UTC, elsevers commented on tools/magnet/plumbing/document/solution/mn_getCoilFlux.m
> +function dataPoints = mn_getCoilFlux(mn, doc, compName, pid)
We already have the function `mn_readCoilFluxLinkage()`. Please take a look -- if the existing function is sufficient, let's not add this new function.

2019-05-20 18:24 UTC, elsevers commented on tools/magnet/plumbing/document/solution/mn_getCoilVoltage.m
> +function dataPoints = mn_getCoilVoltage(mn, doc, compName, pid)
`mn_readCoilVoltage()` already exists.

2019-05-20 18:24 UTC, elsevers commented on tools/magnet/plumbing/document/solution/mn_getComponentForce.m
> +function dataPoints = mn_getComponentForce(mn, doc, compName, pid, axis)
We already have `mn_readForceOnBody()`

2019-05-23 05:47 UTC, ngadiyar93 commented
I have made the changes suggested and the PR is ready for review.

2019-05-30 03:39 UTC, elsevers requested changes
Getting closer, but more work is still needed.

2019-05-30 03:39 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_setEvenPeriodic.m
> +invoke(mn, 'processcommand', sprintf('call getDocument.setEvenPeriodic("%s",Null,Null,Null,Null,ShiftVector,Null)',name));
Since we are adding this as a plumbing function, the pattern to follow is to make your argument list as close to the actual functions argument list as possible. This means you should make the following changes:
1. You should not have `x, y, z` as separate arguments. Rather, they should be one array (`shiftVector`?), as listed in the MagNet `setEvenPeriodic` function
2. It appears that you have only implemented a couple of the arguments of `setEvenPeriodic()`. Please add support for all arguments (I am referring to all of the nulls). If this is not possible, then make your function compatible with the full argument list so that functionality can be added later.
3. Does MagNet's `setEvenPeriodic()` return a value? If so, it should be returned from this function.

2019-05-30 03:39 UTC, elsevers commented on tools/magnet/porcelain/mn_d_createEvenPeriodicBoundaryCondition.m
> +cmdstring = sprintf('call getDocument.createBoundaryCondition(nmArray,"%s")', name);
This should be a call to the function you have created `mn_d_createBoundaryCondition()` instead of calling it directly here

2019-05-30 03:39 UTC, elsevers commented on tools/magnet/porcelain/mn_d_createEvenPeriodicBoundaryCondition.m
> +invoke(mn, 'processcommand', sprintf('call getDocument.setEvenPeriodic("%s",Null,Null,Null,Null,ShiftVector,Null)',name));
This should be a call to the function you have created `mn_d_setEvenPeriodic()` instead of calling MagNet's function directly here

2019-05-30 03:39 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_makeMotionComponent.m
> +function [motion] = mn_d_makeMotionComponent(mn, problemID, surfacesVolume)
Why is `problemID` an argument? It seems that this is not used in this function...

2019-05-30 06:32 UTC, ngadiyar93 commented on tools/magnet/plumbing/document/mn_d_setEvenPeriodic.m
> +invoke(mn, 'processcommand', sprintf('call getDocument.setEvenPeriodic("%s",Null,Null,Null,Null,ShiftVector,Null)',name));
I have made these changes. 
MagNet's setEvenPeriodic() doesn't return a value.

2019-06-01 14:21 UTC, elsevers requested changes
I have found several problems. Please address my concerns. 

Moreover, you need to take a careful look at your code. Please check for whitespace errors (unnecessary spaces, missing spaces, etc.), variable names that do not follow the eMach style guide or do not accurately reflect the variable they are describing, inaccurate or incomplete comments, and MagNet functions that do not match the MagNet documentation for the function they are wrapping. 

Please test your code before requesting another review of your PR.

2019-06-01 14:21 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_setEvenPeriodic.m
> +arguments = sprintf('"%s",%s,%s,%s, %s, %s, %s',...
This file does not appear to ever actually make the  setting change?

You should have a test that validates that your code is working. Where is that test? (_And it surely must be failing right now_)

2019-06-01 14:21 UTC, elsevers commented on tools/magnet/porcelain/mn_d_createEvenPeriodicBoundaryCondition.m
> +mn_d_setEvenPeriodic(mn, name,scale_factor, rotation_angle, RotationAxis, MirrorNormal, ShiftVector, Center);
Please clean up the white space errors here. (i.e., there should be a space between `name,` and `scale_factor`)

2019-06-01 14:21 UTC, elsevers commented on tools/magnet/porcelain/mn_d_createEvenPeriodicBoundaryCondition.m
> +mn_d_createBoundaryCondition(mn, surfacesFace, Face , name );
Please clean up the white space errors (there should be no space between `Face` and `,`)

2019-06-01 14:21 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_createBoundaryCondition.m
> +function mn_d_createBoundaryCondition(mn, surfacesFace, Face , name )
1. There are several whitespace errors in this function declaration. Please be check your code to eliminate whitespace errors.

1. However, more concerning is that this is not the proper implementation of this function. It is not general to assume that the boundary condition will be applied to the same face of each component. Instead, you need to view the array that you pass in here as being an array of paths. A complete path includes a component (and possibly also a face of the component), as documented in the MagNet documentation for this function.
   - Please change your function definition to  `function mn_d_createBoundaryCondition(mn, pathArray, name)`
   - When you use the function, your code should look like this: `bcPath = mn_d_createBoundaryCondition(toolMn.mn, [{'Volume 1, Face#1'}, {'Volume2'}], 'rotorMotion');`

1. According to the MagNet documentation this function should return a string which is a path to the boundary condition that was just created. Please implement this.

2019-06-01 14:21 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_makeMotionComponent.m
> +function [motion] = mn_d_makeMotionComponent(mn, surfacesVolume)
According to the MagNet documentation, this should be a cell array of component names. `surfacesVolume` is not an accurate description. Please replace `surfacesVolume` with `componentNames` (or something equivalent)

2019-06-01 14:21 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_setEvenPeriodic.m
> +function mn_d_setEvenPeriodic(mn, name,scale_factor, rotation_angle, RotationAxis, MirrorNormal, ShiftVector, Center)
1. According to the MagNet documentation, this function needs to return a value: true (or 1) if successful, false (or 0) if unsuccessful. Please implement this.

2. Please update the argument names to following the style guide for eMach. I.e., `scale_factor` should be `scaleFactor`. 

3. In general, I would like you to give more thought to your argument names here. Please make them more consistent with each other and with the MagNet function documentation.

2019-06-01 14:21 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_setEvenPeriodic.m
> +if strcmp(ShiftVector,'Null')== 0
Instead of the user passing in a string of `Null`, the user should pass in an empty array `[ ]`. You can then check this by using the `isempty()` function. So line 12 would be:

`if ~isempty(shiftVector)`

Please apply this to the other vectors which can be null.

2019-06-02 20:32 UTC, ngadiyar93 commented on tools/magnet/plumbing/document/mn_d_setEvenPeriodic.m
> +arguments = sprintf('"%s",%s,%s,%s, %s, %s, %s',...
I am not sure how this happened. Most likely I hadn't pushed once I made the update, as the version here has a line missing which actually makes the settings in MagNet. 
I have corrected this now and tested it works.

The test for now would be running the TransientSolveAFPM2DExample.m file located in `examples/exampleAFPM2D` which draws the machine, sets the conditions and solves it.

2020-08-05 13:30 UTC, ngadiyar93 commented
> I have found several problems. Please address my concerns.
> 
> Moreover, you need to take a careful look at your code. Please check for whitespace errors (unnecessary spaces, missing spaces, etc.), variable names that do not follow the eMach style guide or do not accurately reflect the variable they are describing, inaccurate or incomplete comments, and MagNet functions that do not match the MagNet documentation for the function they are wrapping.
> 
> Please test your code before requesting another review of your PR.

2020-08-05 13:32 UTC, ngadiyar93 commented
> I have found several problems. Please address my concerns.
> 
> Moreover, you need to take a careful look at your code. Please check for whitespace errors (unnecessary spaces, missing spaces, etc.), variable names that do not follow the eMach style guide or do not accurately reflect the variable they are describing, inaccurate or incomplete comments, and MagNet functions that do not match the MagNet documentation for the function they are wrapping.
> 
> Please test your code before requesting another review of your PR.

I have implemented the changes

2020-09-12 21:08 UTC, elsevers requested changes
I have reviewed everything except for your changes in the `examples` folder. I

 have identified several items that need to be resolved. Please see my inline comments.

Please take a look through the changes you are proposing in the `examples` folder to make sure it will pass my review.

When you are ready for me to review your code again, please re-request my review.

2020-09-12 21:08 UTC, elsevers commented on tools/magnet/porcelain/mn_d_createEvenPeriodicBoundaryCondition.m
> +    name, scale_factor, rotation_angle, RotationAxis, MirrorNormal, ShiftVector, Center)
Nearly every argument in this function does not follow our MATLAB [style guidelines](https://github.com/Severson-Group/KnowledgeBase/blob/master/code/matlab/README.md#style-guidelines). Please fix.

Why is there an `_d_` in the function name? That is used in the plumbing commands to signify where they reside in the MagNet scripting hierarchy. It doesn't make sense for porcelain commands.

2020-09-12 21:08 UTC, elsevers commented on tools/magnet/porcelain/mn_d_createEvenPeriodicBoundaryCondition.m
> +mn_d_setEvenPeriodic(mn, name, scale_factor, rotation_angle, RotationAxis, MirrorNormal, ShiftVector, Center);
It sure doesn't seem like `mn_d_createEvenPeriodicBoundaryCondition` does much. Why create this function instead of just use the plumbing commands?

2020-09-12 21:08 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_setEvenPeriodic.m
> +%   center: reference point coordinates in (mm)
The function comments do not follow our matlab style guidelines. Compare this to other functions and you will see the differences (the use of `:`, return value is not specified, etc.)

2020-09-12 21:08 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_makeMotionComponent.m
> +%   This is a wrapper for Document::makeMotionComponent
This function's comments are not consistent with our style.

Please identify standard function comment style. If we don't have it properly documented in the [knowledgebase](https://github.com/Severson-Group/KnowledgeBase/blob/master/code/matlab/README.md#style-guidelines) please create a PR in the knowledgebase to add the necessary documentation.

2020-09-12 21:08 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_createBoundaryCondition.m
> +%   name: name assigned to the boundary condition
Why does name have a `:` after it?

2020-09-12 21:08 UTC, elsevers commented on tools/magnet/plumbing/document/mn_d_createBoundaryCondition.m
> +%   This is a wrapper for Document::createBoundaryCondition
Where is the info on what is returned?

2020-09-12 21:08 UTC, elsevers commented on tools/magnet/MagNet.m
> +            cores = sprintf('Call getDocument().setNumberOfMultiCoreSolveThreads(%i)',numCores);
There should be an empty line between the end of the description and the first line of code

2020-09-12 22:10 UTC, ngadiyar93 commented on tools/magnet/porcelain/mn_d_createEvenPeriodicBoundaryCondition.m
> +mn_d_setEvenPeriodic(mn, name, scale_factor, rotation_angle, RotationAxis, MirrorNormal, ShiftVector, Center);
This was a redundant function I think I originally created. Yes, it doesn't make sense to have it anymore. Even the example doesn't use this - it uses the plumbing commands.

Deleting this..

2020-09-13 14:13 UTC, elsevers commented
@ngadiyar93 I went through the broader repository and I agree that our comment/documentation issue is widespread. Let's address the documentation issues in a separate PR. If you feel you have addressed my other requests and you are happy with the `examples` content please re-request my review. Thanks.

2020-09-17 22:56 UTC, ngadiyar93 commented
> @ngadiyar93 I went through the broader repository and I agree that our comment/documentation issue is widespread. Let's address the documentation issues in a separate PR. If you feel you have addressed my other requests and you are happy with the `examples` content please re-request my review. Thanks.

The PR can be re-reviewed. I have addressed the issues and also tweaked content in the examples folder. I have saved documentation updates for another PR .

2020-09-27 18:32 UTC, elsevers requested changes
@ngadiyar93 -- nice work. This is shaping up to be a terrific example! 

I have one request/question that I would like you to address (flagged in your code). Apart from this, I have made some corrections directly to the code for you to merge in.

Upon completing this, I am ready to approve your PR. Please collect one more review from the current eMach team.

2020-09-27 18:32 UTC, elsevers commented on examples/exampleAFPM2D/ConstructAFPM2DExample.m
> +        'material', MaterialGeneric('name', 'Recoma 33E;Type=Uniform;Direction=[0,-1,0]'), ... % Recoma 35 E
Why is there a comment here that says Recoma 35E?

2020-09-27 18:39 UTC, ngadiyar93 commented on examples/exampleAFPM2D/ConstructAFPM2DExample.m
> +        'material', MaterialGeneric('name', 'Recoma 33E;Type=Uniform;Direction=[0,-1,0]'), ... % Recoma 35 E
@elsevers Oops, this was an error that I missed fixing. It had to be Recoma 33E. I have updated it now.

2020-09-27 18:43 UTC, ngadiyar93 commented
> @ngadiyar93 -- nice work. This is shaping up to be a terrific example!
> 
> I have one request/question that I would like you to address (flagged in your code). Apart from this, I have made some corrections directly to the code for you to merge in.
> 
> Upon completing this, I am ready to approve your PR. Please collect one more review from the current eMach team.

@elsevers I have merged the patch, and also updated the comment to reflect the appropriate PM material.

2020-09-27 18:56 UTC, elsevers requested changes

2020-09-27 18:56 UTC, elsevers commented on examples/exampleAFPM2D/ConstructAFPM2DExample.m
> +        'material', MaterialGeneric('name', 'Recoma 33E;Type=Uniform;Direction=[0,-1,0]'), ... % Recoma 33 E
@ngadiyar93 I think you should remove this comment. 

I don't understand why this line of code should have a `Recoma 33 E` comment when other lines that assign the magnet do not. I also don't see why it is necessary given the that material is current self-described (`Recoma 33E` is the name of the material)

2020-09-27 19:00 UTC, ngadiyar93 commented on examples/exampleAFPM2D/ConstructAFPM2DExample.m
> +        'material', MaterialGeneric('name', 'Recoma 33E;Type=Uniform;Direction=[0,-1,0]'), ... % Recoma 33 E
@elsevers I have removed the `Recoma 33E` comments

2020-09-27 19:23 UTC, elsevers approved these changes
Nice work @ngadiyar93! I am ready to approve now.

2020-09-27 19:31 UTC, Bharat-Ramadas approved these changes
Works fine

2020-09-27 19:32 UTC, merged

2020-09-27 19:32 UTC, ngadiyar93 commented
@elsevers @Bharat-Ramadas thanks for your reviews. I just hit the merge button.