Add crossections
Severson-Group/eMach-matlab pull request #112
Opened 2020-09-24 18:04 UTC by ngadiyar93

Add crosssects that were developed for conical PM bearing modeling.

2020-09-27 19:29 UTC, Bharat-Ramadas approved these changes, later dismissed
Works fine

2020-09-27 21:01 UTC, elsevers requested changes
Nice job. I have a question about the `x_coord` calculation that I have inserted as an inline comment.

In the drawing, please make your label text consistent with other figures by italicizing your variable names.

2020-09-27 21:01 UTC, elsevers commented on model_obj/crosssects/parallelogram/CrossSectParallelogram.m
> +            x_coord = (l*cos(theta)+ t/sin(theta))/2;
I am not sure about your `x_coord` math. Can you please explain it in a response to this comment?

2020-10-01 20:27 UTC, ngadiyar93 commented on model_obj/crosssects/parallelogram/CrossSectParallelogram.m
> +            x_coord = (l*cos(theta)+ t/sin(theta))/2;
The array `x` has the x-coordinates of the 4 points forming the parallelogram.
`x_coord` basically is the coordinate of a point **inside** the surface to extrude. Ideally we would want it to be the mid-point.
 
Because this is a parallelogram and no two points have the same x coordinates, what @wchan29 did here was take the x_coord equal to the mid point of the left top point and the right bottom point. (I have circled the points here).

![image](https://user-images.githubusercontent.com/43225038/94859685-88fe3300-03fa-11eb-8a48-30635130efdf.png)

2020-10-02 15:22 UTC, elsevers approved these changes
Thanks @ngadiyar93. This looks good to me.

2020-10-02 19:58 UTC, Bharat-Ramadas approved these changes
Looks good

2020-10-02 20:00 UTC, merged