Add MATLAB code documentation convention
Severson-Group/eMach-matlab pull request #121
Opened 2020-10-01 22:07 UTC by ngadiyar93

This PR adds the Matlab code documentation convention.

This is a draft pull request in progress. Not ready for review

2020-10-11 01:44 UTC, elsevers requested changes
Nice @ngadiyar93! I agree in general with the guidelines, but I am not convinced that this is presented in the best way and I think that details are getting missed. See my specific comments in-line as well as the following items:

- Instead of inserting screenshots of code (which are an inefficient use of space in the repository and render blurry), please use the markdown [code environment](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) and copy-paste your code into the page.

- Avoid using the word "hence"

- `MATLAB` should be in all capital letters

- Pay closer attention to the details of the MATLAB function documentation. i.e., when should there be whitespace between items? what about multiple function signatures? Your goal here is to effectively draft a specification for these functions.

2020-10-11 01:44 UTC, elsevers commented on README.md
> +Providing clear and concise in-function documentation makes open source code easy to understand and hence more useful. Contributors to eMach should try to follow the Matlab function documentation sty
> Contributors to eMach should try to follow the Matlab function documentation style as closely as possible.

Be more direct: `Contributors to eMach should follow the MATLAB function documentation guidelines.`

2020-10-11 01:44 UTC, elsevers commented on README.md
> +- Throughout the documentation, the function name should be typed in upper case, i.e. `mn_d_makeMotionComponent()` as `MN_D_MAKEMOTIONCOMPONENT()`. If done so, Matlab renders the function name in bol
This first item doesn't seem to belong in the same list as the rest of the items. All other items are describing specific locations in the function documentation. This bullet is actually describing a general guideline that persists throughout the entire function documentation. See how it is different?

2020-10-11 01:44 UTC, elsevers commented on README.md
> +- The function signature is provided next. Example: `motion = MN_D_MAKEMOTIONCOMPONENT(mn, componentName) creates a motion component to move the geometry named componentName`
In MATLAB's documentation, a function signature is provided and followed immediately by a brief one sentence description of what that function accomplishes with that function signature. You forgot to mention that one sentence description. Please mention it. Is it always one sentence? Is it ever longer?

2020-10-11 01:44 UTC, elsevers commented on README.md
> +- The function arguments are described for different use cases. Example: `mn is the MagNet object. componentName is a string containing the name of the geometry to be included in the motion component
You should be clear that this is expected to directly continue from the function signature. I.e., there is no whitespace vertically between the function signature and the description of arguments. It is part of the same paragraph. Am I right about this? Is it always in the same paragraph or is it ever broken out into additional paragraphs?

2020-10-11 01:44 UTC, elsevers commented on README.md
> +- The return value should be described. Example: `This function returns motion, which is a string containing name of the motion component created`
Clarify that this should now be a separate paragraph from the function signature, brief description, list of arguments. Am I right about this? Is it always broken out into separate paragraphs or should it in fact be part of the same paragraph (refer to MATLAB `help xxx` for examples)

2020-10-11 01:44 UTC, elsevers commented on README.md
> +- Provide example use cases. Be as descriptive as possible. Example: `For example, motion = MN_D_MAKEMOTIONCOMPONENT(mn, 'rotorIron'), creates a motion component to move the geometry 'rotorIron'. mot
Specify each example is in its own paragraph (am I correct about that?). 

The items corresponding to `function signature description` (the missing one that I have asked you to add), `argument description`, `return value description`, and `examples` should actually be sub items underneath `function signature`. Please make these be sub items.

Clarify that functions can have multiple function signatures. And that all function signatures must be described, in order of fewest arguments provided to most arguments provided (it looks like this is how MATLAB library functions are documented) and that each subsequent function signature only adds additional information (it doesn't re-describe arguments/return values previously described)

2020-10-11 01:44 UTC, elsevers commented on README.md
> +- Finally, list related functions. Example: `See also MN_FINDBODY, MN_GETPATHOFRADIALFACES, MN_D_MAKESIMPLECOIL, MN_D_SETDEFAULTLENGTHUNIT, MN_D_SETPARAMETER, MN_D_CREATEBOUNDARYCONDITION.`
A bulleted list implies a list where the order of the items do not matter. However, the order of these items clearly matters. Please use a numbered list. I also suggest having 2 or 3 word bold or italicized headings at the start of each number giving us a title for the item.

The amount of example code in these items is excessive. Please reduce this. Since you are providing us a complete example after this specification, please minimize the amount of inline examples you give in your function documentation specification.

2020-10-11 01:44 UTC, elsevers commented on README.md
> +- If applicable, specify what function in the FEA tool, this is a wrapper for. Example: `This is a wrapper for Document::makeMotionComponent`
This feels out of place to specify here. Like under 1 percent of our functions fit into this use case, so why make a reader focus on this when trying to learn how to contribute to our code base? Instead, this instruction should be provided in a `README.md` file in the MagNet tool plumbing folder.

2020-10-16 00:24 UTC, ngadiyar93 commented on README.md
> +- The function signature is provided next. Example: `motion = MN_D_MAKEMOTIONCOMPONENT(mn, componentName) creates a motion component to move the geometry named componentName`
Yup it is always one sentence in the functions I looked at.

2020-10-16 00:24 UTC, ngadiyar93 commented on README.md
> +- The return value should be described. Example: `This function returns motion, which is a string containing name of the motion component created`
Yes, it is separate paragraphs. I have updated the document to clarify this

2020-10-16 00:25 UTC, ngadiyar93 commented on README.md
> +- The function arguments are described for different use cases. Example: `mn is the MagNet object. componentName is a string containing the name of the geometry to be included in the motion component
Yup, Function signature + argument description is a single paragraph - no vertical white spaces.

2020-10-16 00:25 UTC, ngadiyar93 commented on README.md
> +- Throughout the documentation, the function name should be typed in upper case, i.e. `mn_d_makeMotionComponent()` as `MN_D_MAKEMOTIONCOMPONENT()`. If done so, Matlab renders the function name in bol
Moved it away from this list.

2020-10-19 14:51 UTC, elsevers requested changes
This is looking much better! Nice work @ngadiyar93 and @Bharat-Ramadas. I have several requests that I have indicated below.

2020-10-19 14:51 UTC, elsevers commented on README.md
> +- Follow the MATLAB editor guidelines on maximum line length
Missing a period at the end of this sentence.

2020-10-19 14:51 UTC, elsevers commented on README.md
> +Throughout the documentation, the function name should be typed in upper case, i.e. `mn_d_makeMotionComponent()` as `MN_D_MAKEMOTIONCOMPONENT()`. If done so, MATLAB renders the function name in bold
> Throughout the documentation, the function name should be typed in upper case, i.e. `mn_d_makeMotionComponent()` as `MN_D_MAKEMOTIONCOMPONENT()`. If done so, MATLAB renders the function name in bold face.

This should be a new paragraph

2020-10-19 14:51 UTC, elsevers commented on README.md
> +The salient features of the Matlab documentation style are described with an example below
Instead, how about writing: `The function documentation block should consist of the following components:`

2020-10-19 14:51 UTC, elsevers commented on README.md
> +2. **Function signature:** The function signature is provided next, and has four main parts, as described below
> as described below

how about `as listed below`

2020-10-19 14:51 UTC, elsevers commented on README.md
> +An example function documentation will look as follows
Replace with `Here is an example of a function documentation block that follows this specification:`

2020-10-19 14:51 UTC, elsevers commented on README.md
> +Notice the indentation in the above screenshot. This is consistent with Matlab style. Specifically, the following are to be noted
> Notice the indentation in the above screenshot.

First, this is no longer a screenshot.

Revise to treat this part as a specification on indentation (or horizontal whitespace). Also, if you look closely at MATLAB's documentation, you'll  see that they aren't using `tab` characters, they are actually using three space characters (in otherword, one tab = 3 spaces)

Remember to capitalize MATLAB

2020-11-13 13:47 UTC, ngadiyar93 commented
This PR can be reviewed

2020-11-13 16:07 UTC, mwjohnson56 submitted a review, later dismissed
This looks good to me. Documentation is much clearer compared to the previous version and follows the conventions you set forward in the EMACH meetings.

2020-11-20 17:15 UTC, elsevers requested changes
Nice job. Add missing colons.

2020-12-03 15:40 UTC, ngadiyar93 commented
@elsevers @mwjohnson56 I have made the changes. This PR can be reviewed.

2021-02-19 17:47 UTC, ASHAD1 commented
@ngadiyar93 This looks good. There are few typos in the document, marked in the attached snip, and also the link under **Code Style** section is not working. I was not able to comment on directly because the changes were not done in this PR but it belongs the same document. Other than that looks good.
![image](https://user-images.githubusercontent.com/12862027/108541454-16f29180-72a8-11eb-93af-ca4b19c586f4.png)

2021-02-19 17:57 UTC, ngadiyar93 commented
> 
> 
> @ngadiyar93 This looks good. There are few typos in the document, marked in the attached snip, and also the link under **Code Style** section is not working. I was not able to comment on directly because the changes were not done in this PR but it belongs the same document. Other than that looks good.
> ![image](https://user-images.githubusercontent.com/12862027/108541454-16f29180-72a8-11eb-93af-ca4b19c586f4.png)

@ASHAD1 I have fixed the typo. I am not too sure where the hyperlink should point to.

In case it wasn't clear, the scope of this PR is only the `In Function Documentation` section of the markdown document.

2021-02-23 20:56 UTC, ASHAD1 submitted a review, later dismissed

2021-02-24 04:05 UTC, Bharat-Ramadas commented on README.md
> +Using a consist writing style makes shared code more maintainable, useful, and understandable. Contributors to eMach should follow the guidelines provided [here](https://www.mathworks.com/matlabcentr
I think you meant consistent* here

2021-02-25 02:45 UTC, Bharat-Ramadas submitted a review, later dismissed
Looks good to me

2021-02-25 18:29 UTC, elsevers approved these changes

2021-02-25 18:31 UTC, ASHAD1 approved these changes

2021-02-25 18:32 UTC, merged