Add JMAG tool
Severson-Group/eMach-matlab pull request #131
Opened 2020-11-06 02:03 UTC by ngadiyar93

This PR adds JMAG tool to eMach. Primarily done by @ASHAD1 with some support from @ngadiyar93. It is heavily based on Jiahao Chen's work from Spring 2019.

To explore the JMAG tool, please check out this branch and run `outerRotorStatorExample.m` from the examples folder.
You should be able to see the stator of an outer rotor machine drawn both in MagNet and in JMAG.

**Note:** This is a draft PR. More features are to be added / modified based on feedback from the larger team discussion.

2020-12-20 17:39 UTC, ngadiyar93 commented
@ASHAD1 The `DimMeter` is added in this PR, as well as updates to `DimMillimeter` are made here. Do you want to add those as separate PRs? Maybe we only want to limit this PR to adding the JMAG tool (and examples)?

2021-02-11 14:51 UTC, ASHAD1 commented
@ngadiyar93 I agree with your earlier comment. So this PR doesn't include changes in the dimensions class. The `DimMeter` class was added in another PR to develop branch, and I have pulled the latest develop changes in this branch.

2021-02-17 22:08 UTC, Bharat-Ramadas commented on examples/twoOuterRotorStator.m
> +        'name', 'stator1', ...
Please revise name to 'stator2'

2021-02-17 22:10 UTC, Bharat-Ramadas commented on examples/xfemmExampleArc.m
Looks like this is an xFemm example file. Do you want to include this in the PR?

2021-02-17 22:11 UTC, Bharat-Ramadas commented on examples/xfemmExampleNotchedRectangle.m
Looks like this is an xFemm example file. Do you want to include this in the PR?

2021-02-19 16:46 UTC, ngadiyar93 commented on examples/twoOuterRotorStator.m
> +        'name', 'stator1', ...
@Bharat-Ramadas Done :-)

2021-02-19 16:46 UTC, ngadiyar93 commented on examples/xfemmExampleNotchedRectangle.m
Removed this

2021-02-19 16:47 UTC, ngadiyar93 commented
@aimthiazz @Bharat-Ramadas I have worked to address your feedback from the review we had earlier this week.

2021-02-19 17:30 UTC, aimthiazz approved these changes, later dismissed
Checked it in my system.

2021-02-20 18:55 UTC, Bharat-Ramadas submitted a review, later dismissed
Looks good to me.

2021-02-25 21:29 UTC, elsevers requested changes
See detailed requests in the comments.

2021-02-25 21:29 UTC, elsevers commented on tools/jmag/JMAG.m
> +        defaultAngle = 'degrees'; % Default angle unit is degrees
Let's make `defaultLength` and `defaultAngle` be strings that correspond to class names of dimension objects, so that `feval` can be used to do the unit conversion

2021-02-25 21:29 UTC, elsevers commented on tools/jmag/JMAG.m
> +                obj.model.SetUnitCollection('SI_units')
Need to update `self.defaultLength` to `DimMeter`

2021-02-25 21:29 UTC, elsevers commented on tools/jmag/JMAG.m
> +                obj.model.SetUnitCollection('SI_units')
Need to update `self.defaultAngle` to `DimDegree`

2021-02-25 21:29 UTC, elsevers commented on tools/jmag/JMAG.m
> +        function convertedLength = convertLengthUnit(obj, length, userUnit)
Eliminate this function and instead just use `feval` combined with `defaultLength` inside the functions that need to convert units

2021-02-25 21:29 UTC, elsevers commented on tools/jmag/JMAG.m
> +        function convertedAngle = convertAngleUnit(obj, angle, userUnit)
Eliminate this function and instead just use `feval` combined with `defaultAngle` inside the functions that need to convert units

2021-02-25 21:29 UTC, elsevers commented on examples/outerRotorStatorExample.m
> +        'material', MaterialGeneric('name', '10JNEX900'), ...
This looks like it will break MagNet. We can't merge the code if it will break another tool.

Need to fix the examples so that MagNet still works. *Please verify.*

2021-03-06 22:29 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +        defaultAngle = 'degrees'; % Default angle unit is degrees
Updated in the latest commit.

2021-03-06 22:38 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +                obj.model.SetUnitCollection('SI_units')
Updated in the latest commit.

2021-03-06 22:38 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +                obj.model.SetUnitCollection('SI_units')
Updated in the latest commit.

2021-03-06 22:54 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +        function convertedLength = convertLengthUnit(obj, length, userUnit)
Updated in the latest commit.

2021-03-06 22:55 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +        function convertedAngle = convertAngleUnit(obj, angle, userUnit)
Updated.

2021-03-06 23:06 UTC, ASHAD1 commented
@elsevers I think this ready for your review.

2021-03-07 01:37 UTC, Bharat-Ramadas reviewed
Nice job @ASHAD1. Please see my comments

2021-03-07 01:37 UTC, Bharat-Ramadas commented on tools/jmag/JMAG.m
> +            obj.part.CreateExtrudeSolid(ref1,double(DimMeter(depth)))
Shouldn't `depth` be a DimLinear object? I think you should use `feval` here as well.

2021-03-07 01:37 UTC, Bharat-Ramadas commented on tools/jmag/JMAG.m
> +            obj.geomApp.View.SelectAtCoordinateDlg(double(DimMeter(csToken.innerCoord(1))), ...
Should this be `feval` instead of `DimMeter(csToken.innerCoord(1))`?

2021-03-07 20:09 UTC, ngadiyar93 commented on tools/jmag/JMAG.m
> +            obj.geomApp.View.SelectAtCoordinateDlg(double(DimMeter(csToken.innerCoord(1))), ...
Thanks @Bharat-Ramadas I have updated this.

2021-03-07 20:09 UTC, ngadiyar93 commented on tools/jmag/JMAG.m
> +            obj.part.CreateExtrudeSolid(ref1,double(DimMeter(depth)))
Thanks @Bharat-Ramadas I have updated this.

2021-03-07 22:10 UTC, Bharat-Ramadas submitted a review, later dismissed
Looks good

2021-03-11 20:45 UTC, elsevers requested changes

2021-03-11 20:45 UTC, elsevers commented on tools/jmag/JMAG.m
> +        end
Contents of the revolve function are missing

2021-03-11 20:45 UTC, elsevers commented on tools/jmag/JMAG.m
> +        function extrudeSketch = extrude(obj, name, material, depth, csToken)
Please add a couple more comments in this function explaining the process to extrude

2021-03-11 20:45 UTC, elsevers commented on tools/jmag/JMAG.m
> +        function sketch = prepareSection(obj, csToken)
Please add a couple more comments explaining the what is taking place in this function

2021-03-24 22:17 UTC, Bharat-Ramadas reviewed
Please see my comment below

2021-03-24 22:17 UTC, Bharat-Ramadas commented on tools/jmag/JMAG.m
> +            center = double(feval(obj.defaultLength, center));
Is there a reason for converting the DimLinear objects to double?

2021-03-25 03:58 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +            center = double(feval(obj.defaultLength, center));
The arguments that are passed to the JMAG functions need to be data type double.

2021-03-26 00:19 UTC, elsevers requested changes
`twoOuterRotorStator.m` example does not work. I immediately get a MATLAB error, see below. It looks like you have hard coded this to only work for JMAG 18.1. This code needs to work with any version of JMAG. **Please fix**

![image](https://user-images.githubusercontent.com/7421348/112559411-fd5cd200-8d9e-11eb-9515-5d5d7fd3d9b8.png)

2021-03-26 00:19 UTC, elsevers commented on tools/jmag/JMAG.m
> +            center = double(feval(obj.defaultLength, center));
This does not make sense. All dimensions are type `double`. We should not be converting them to doubles from their respective classes.

2021-03-26 01:25 UTC, elsevers requested changes
Please resolve all merge conflicts. Then, merge the latest `develop` branch into this branch and make the JMAG tool compliant with the latest version of the `ToolBase` class.

Go through my detailed comments below. 

Finally, go function by function and compare your JMAG tool to the latest version of the MagNet tool. Think about what differences there should be between the MATLAB implementation of the two tools and what should be the same.

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/JMAG.m
> +        sketchList;
Please review your properties: make sure that all of these are needed and update the property names to be more consistent with each other and meaningful.

In particular, please rename `geomApp` (perhaps `geometryEditor`?). Why do we have both `app` and `jd`? This looks like a duplicate reference to the same object.

Why are you setting these to 0 when they are not used? Please revise to be consistent with how the `MagNet` tool is implemented (they are simply not initialized)

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/JMAG.m
> +        function obj = open(obj, varargin)
Please update this to implement the function signature in the newly revised `ToolBase`

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/JMAG.m
> +        function save(obj, path, fileName)
Please revise to use the new function signature in the updated `ToolBase`

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/JMAG.m
> +        end
Please add a `saveAs` function

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/JMAG.m
> +            endxy = double(feval(obj.defaultLength, endxy));
These should not be converted to `double`

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/JMAG.m
> +            end
Why do we have to do this check every time `drawArc` or `drawLine` are called? Shouldn't the `sketch` property get initialized in the `open` function and then never have to be updated?

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/JMAG.m
> +            obj.app.Save()
`obj.app.Save()`

Why are you saving after you extrude/revolve a part? Wouldn't it be better for the user to call the save function for the tool? (What if a user wants to extrude something but not save the results?)

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/JMAG.m
> +            sketch = 1;
`sketch = 1;`

I don't understand what is going on with your `sketch` property and why it is getting updated like this.

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/README.md
> +Although this workflow is consistent with the workflow in Infolytica MagNet, the workflow in JMAG has some additional steps to be followed. The JMAG workflow is as follows:
Don't be talking about MagNet here. Just talk about eMach and JMAG.

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/README.md
> +2. Extrude the cross section - requires a coordinate that is inside the region to be extruded.
This item 2 is written too casually. Revise your language to be more professional.

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/README.md
> +In the JMAG workflow, steps 2. and 3. need to be suitably handled. This is because, the JMAG function to create regions simply converts any closed geometry (bounded by lines and arcs) into a JMAG geo
`steps 2. and 3.` 
Don't put periods after these numbers

`This is because, the...` - language and grammar revision are needed

`JMAG geometry region` -- language issue here. What is noun you mean? Does simply `region` (no `JMAG geometry`)?

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/README.md
> +For example, if a stator cross-section of a radial flux machine is drawn, JMAG creates two regions - one the actual stator region comprising the teeth, yoke etc, and the other region comprising the s
Language issues/revision needed

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/README.md
> +If working with the JMAG's gui, one can select the region that is not required and delete it manually. However, this is hard to do programmatically because of the following reasons:
`gui` should be in all capital letters.

2021-03-26 01:25 UTC, elsevers commented on tools/jmag/README.md
> +1. The `CreateRegions()` function in JMAG takes no arguments - i.e, there is no way to specify where to create JMAG geometry regions. All closed geometries are simply converted to JMAG geometry regio
This does not belong here: `- i.e.`. Please revise your language to be more professional.

2021-03-26 03:15 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +            center = double(feval(obj.defaultLength, center));
I am not sure about that unless it's converted to double JMAG was throwing an error.

2021-03-26 14:06 UTC, ngadiyar93 commented on tools/jmag/JMAG.m
> +            center = double(feval(obj.defaultLength, center));
@Bharat-Ramadas and @elsevers I agree. However, when I checked, I too found that @ASHAD1 is right -- unless converted to double, JMAG throws an error. 

The following test script can be used to quickly check this:

```matlab
%%  Initialize JMAG
toolJd = JMAG();
toolJd.setVisibility(true);
toolJd.open();
toolJd.sketch = toolJd.getSketch(0);
toolJd.sketch.OpenSketch();

%%  Draw the first vertex with coords in double
a = 1;
b = 2;
toolJd.sketch.CreateVertex(a, b);

%%  Draw a second vertex in DimMeters
c = DimMeter(3);
d = DimMeter(4);
toolJd.sketch.CreateVertex(c, d);

```

It runs fine until the last line, but throws the following error on the last line:
![image](https://user-images.githubusercontent.com/43225038/112642757-a04e3400-8e11-11eb-879b-884bcd7f293d.png)

I am guessing this could be because we are using JMAG functions directly, and JMAG has no info on the `DimMeter` data type. This is unlike MagNet where we do an invoke and pass in a string: 
![image](https://user-images.githubusercontent.com/43225038/112643066-f327eb80-8e11-11eb-91e7-358ae2edf4f1.png)

2021-03-26 14:27 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +        sketchList;
I have implemented this.

2021-03-26 14:48 UTC, elsevers commented on tools/jmag/JMAG.m
> +            center = double(feval(obj.defaultLength, center));
Unless anyone else has ideas on how to debug further, it is okay to proceed by converting these to `double`

2021-03-26 16:15 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +            % CLOSE Closes the JMAG document
I have not implemented anything in the `close` function because there is nothing equivalent to closing the document in JMAG. JMAG supports just one project per instance. I have illustrated this using the following example.

Let's say if have a project opened in JMAG and if I try to open a new project as shown in the following screenshot. 
![Screenshot (26)](https://user-images.githubusercontent.com/12862027/112659830-c6c89b00-8e22-11eb-97c2-44fb734bfdbe.png)

When I create a new project, it automatically closes the previous project and opened a new project.

I am running the script recording, using this we can see via scripts what JMAG is doing. In the following screenshot it can be seen that the script recorded only creating a new project, it didn't record any closing command.
![image](https://user-images.githubusercontent.com/12862027/112660915-fa57f500-8e23-11eb-9b8e-b97d250c32f9.png)

So I think JMAG currently doesn't support command for closing a project. @elsevers Please let me know your suggestions on this.

2021-03-26 23:35 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +            end
For every new component, a new sketch (and part) is created. I updated this part of the code. Please review the updated code.

2021-04-04 17:25 UTC, Bharat-Ramadas commented on tools/jmag/JMAG.m
> +            % CLOSE Closes the JMAG document
Hello @ASHAD1. I was going through the JMAG Script help and found a `CloseInstance( )` function there. Maybe this can be used here? 

![image](https://user-images.githubusercontent.com/70265814/113516516-4a5b5800-9598-11eb-9fe9-5d107c769e8d.png)

Also please find below the definition for the Quit( ) function we normally employ when closing JMAG.
![image](https://user-images.githubusercontent.com/70265814/113516560-87bfe580-9598-11eb-8645-33ca50023981.png)

And finally this is the entire list of Public Member Functions available to the `InstanceManager` class in JMAG.
![image](https://user-images.githubusercontent.com/70265814/113516605-ca81bd80-9598-11eb-92ea-041b1549d692.png)

2021-04-04 17:31 UTC, Bharat-Ramadas reviewed
Hello @ASHAD1, @ngadiyar93. Nice work! I have just one comment on the close( ) function.

2021-04-06 20:19 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +            % CLOSE Closes the JMAG document
Interesting find @Bharat-Ramadas. Now I am using this `InstanceManager()` for opening and quitting the JMAG application now. Previously when I was closing JMAG application using `delete(toolJd)`, all the JMAG instances previously opened were closing. Now if I call `delete(toolJd)` (similar to Magnet implementation) it will now only quit the JMAG application instance opened from Emach. 

However, this will not help the `close()` implementation. As per Magnet implementation `close()` should close the document, not the JMAG application instance itself. The Jmag application instance is closed when `delete()` is called. Therefore I have not implemented `close()` in JMAG. @elsevers please let me know if this fine for now.

2021-04-07 00:39 UTC, Bharat-Ramadas approved these changes, later dismissed
Looks good!

2021-04-12 01:08 UTC, elsevers requested changes
This is getting closer, but several issues remain that need to be resolved. See the bug I report here as well as the in-line comments for `JMAG.m`

When I create multiple objects of the JMAG class, each object is re-using the same JMAG instance. For example, if I run this code:
```matlab
toolJd1 = JMAG();
toolJd2 = JMAG();
```
I want that two JMAG windows to open up. But only one window opens. This is because both `toolJd1` and `toolJd2` are re-using the same JMAG application instance. Please fix this. We want to be able to have multiple JMAG windows open at one time.
This is not the

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/JMAG.m
> +            % CLOSE Closes the JMAG document
A user expects that if they call `close` that future function calls will not edit the document they previously had open. If JMAG does not have a notion of document close feature, the proper functionality of `close` should be to open a new document. That is, `close()` should call `obj.open()` (open an untitled file).

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/JMAG.m
> +                error('Please specify a filename');
You currently have this set up so that `filename` is required. However, we'd like to be able leave `filename` as optional so that a user can create an unsaved project. 

In JMAG Designer, if I do `file`->`new` I see this scripting result:
```
Set app = designer
Call app.NewProject("Untitled")
```

If I then click save, JMAG Designer prompts me for a filename to save it as. So it does appear that JMAG allows you to create a new, unsaved project. We should support this as well.

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/JMAG.m
> +    end
Why are we saving `jdInstance`? It looks like this is never actually used. Let's get rid of it.

`geometryEditor` also looks like something we do not need to be saving. The one time it is used is the context of `obj.geometryEditor.view.SelectAtCoordinateDlg()` -- couldn't you just use `obj.view.SelectAtCoordinateDlg()`?

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/JMAG.m
> +        function setVisibility(obj, visibile)
You have misspelled visible here

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/JMAG.m
> +            end
Keep your code DRY. Instead of
```matlab
            if obj.visible
                obj.jd.Show();
            else
                obj.jd.Hide();
            end
```

Call `obj.setVisibility(obj.visible);`

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/JMAG.m
> +            end
You forgot to update `obj.fileName` when you call `obj.jd.Load()`

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/JMAG.m
> +        end
I am not familiar enough with JMAG to be certain about this, but it seems like there probably should be a function call to `setDefaultLengthUnit` and `setDefaultAngleUnit` when you open a new document.

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/JMAG.m
> +            obj.setDefaultAngleUnit(obj.defaultAngle)
Is it really necessary to call these functions here?

```matlab
            obj.setDefaultLengthUnit(obj.defaultLength)
            obj.setDefaultAngleUnit(obj.defaultAngle)
```

Or can they just be called upon opening a file?

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/JMAG.m
> +classdef JMAG < ToolBase & DrawerBase & MakerExtrudeBase & MakerRevolveBase
Since there are multiple JMAG tools, we had better be explicit that this tool is for JMAG-Designer. Please rename this class as `JMAG_Designer`.

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/README.md
> +Although the geometry creation workflow in JMAG is quite consistent with the eMach workflow, one of the important differences is the creation of regions.
Let's cut this first sentence. It does not make sense to try to parse out whether there is a difference between the JMAG and eMach workflow.

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/README.md
> +## The solution
Rename this heading to `## Implementation in eMach`

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/README.md
> +The eMach workflow provides a coordinate `innerCoord` inside every cross section to be extruded. This `innerCoord` will be inside a geometry region that must be retained and extruded in JMAG. With th
Instead of _workaround was adopted to address the issue of multiple geometry regions:_

say _approach is used to create only the desired geometry region:_

2021-04-12 01:08 UTC, elsevers commented on tools/jmag/README.md
> +**Note:** The steps listed above to delete the undesired regions heavily rely on JMAG's region naming convention. If future versions of JMAG updates the way geometry regions are named, this must be u
Remove the word _heavily_

Change _updates the way geometry regions are named_ to _update the naming of geometry regions_

Change _this must be updated accordingly_ to _the JMAG implementation will need to be revised._

2021-04-12 01:22 UTC, elsevers commented
I also don't think that the `delete` function is working properly. If I clear my MATLAB workspace (`clear`), JMAG does not exit. However, if I try the same thing with MagNet, MagNet exits.

2021-04-14 12:03 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +            % CLOSE Closes the JMAG document
This is implemented.

2021-04-14 12:04 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +                error('Please specify a filename');
This is implemented.

2021-04-14 12:07 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +    end
I have removed `jdInstance` from the properties. But I was not able to do it for `geometryEditor`. It will throw an error if I just use `obj.view.SelectAtCoordinateDlg()` instead of `obj.geometryEditor.view.SelectAtCoordinateDlg()`. Let me know if this is fine.

2021-04-14 12:30 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +        end
In JMAG, `units` are associated with the JMAG `model`. We cannot assign units until we have the `model` imported from the `Geometry Editor` to the `JMAG Designer`. Setting units in JMAG is a bit tricky, I have implemented the workflow for setting units as per the workflow we had agreed upon.

2021-04-14 12:31 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +            obj.setDefaultAngleUnit(obj.defaultAngle)
In JMAG, `units` are associated with the JMAG `model`. We cannot assign units until we have the `model` imported from the `Geometry Editor` to the `JMAG Designer`. Setting units in JMAG is a bit tricky, I have implemented the workflow for setting units as per the workflow we had agreed upon.

2021-04-14 12:34 UTC, ASHAD1 commented on tools/jmag/JMAG.m
> +            % CLOSE Closes the JMAG document
This is implemented

2021-04-14 18:01 UTC, ASHAD1 commented
> I also don't think that the `delete` function is working properly. If I clear my MATLAB workspace (`clear`), JMAG does not exit. However, if I try the same thing with MagNet, MagNet exits.

I have fixed this issue in the latest commit.

2021-04-15 00:59 UTC, elsevers requested changes
Please update your function comments to follow the [eMach function comment guidelines](https://github.com/severson-group/emach#in-function-documentation)

--------------

I tried modifying the `exampleLinearMotor.m` file to use this tool and ran into issues.

Here's what I did:

1. Run `exampleLinearMotor.m` -- this will draw the linear machine in MagNet
2. Run these commands:
```matlab
fileName = strcat(path,'\test3.jproj');
toolJd = JMAG_Designer();
toolJd.setVisibility(true);
toolJd.open(fileName);
statorIronComp.make(toolJd, toolJd);
moverIronComp.make(toolJd, toolJd);
magnet1Comp.make(toolJd, toolJd);
magnet2Comp.make(toolJd, toolJd);
magnet3Comp.make(toolJd, toolJd);
```

The end result seems to have two problems:
1. It leaves a JMAG-Designer Geometry editor window open. Is this okay?
2. It has created separate solid models for every single component that was extruded -- see screenshot below:

![image](https://user-images.githubusercontent.com/7421348/114798717-9d34cc80-9d5b-11eb-860e-30343eb34c12.png)

2021-04-15 00:59 UTC, elsevers commented on tools/jmag/JMAG_Designer.m
> +                obj.saveAs('untitled'); % JMAG requires it to be saved before creating geometry
No, we can't assume a location to save a file. This will lead to strange and unexpected behavior down the road.

After doing some digging here, I think you need to go back to requiring that user provide a filename here. You can make it be invalid to call `open` without passing in a file name (to either open or to create). 

Please update your documentation for this function to indicate this. Make sure you follow the [function documentation style for eMach.](https://github.com/severson-group/emach#in-function-documentation)

2021-04-15 00:59 UTC, elsevers commented on tools/jmag/JMAG_Designer.m
> +            %   drawarc(mn, [center_x,_y], [start_x, _y], [end_x, _y])
This function signature comment specifies `mn` as an argument. This is not correct.

2021-04-15 00:59 UTC, elsevers commented on tools/jmag/JMAG_Designer.m
> +                study = obj.model.CreateStudy('Transient', studyName);
How do you know that the study should be `transient`? What does this do?

2021-04-15 00:59 UTC, elsevers commented on tools/jmag/JMAG_Designer.m
> +        function obj = JMAG_Designer(varargin)
After doing some digging on how JMAG handles files, I think you need to go back to requiring that user provide a filename in the initializer. You should then call `obj.open(filename)` in your initializer.

Please update your documentation for this function to indicate this. Make sure you follow the [function documentation style for eMach.](https://github.com/severson-group/emach#in-function-documentation)

2021-04-15 00:59 UTC, elsevers commented on tools/jmag/JMAG_Designer.m
> +        function close(obj)
Yikes. What to do here since our instance of this object always needs to have a valid file? I think that for now, `close` can just call `delete`.

2021-04-15 01:00 UTC, elsevers commented on tools/jmag/JMAG.m
> +    end
Yes, this is okay.

2021-04-18 17:47 UTC, ASHAD1 commented on tools/jmag/JMAG_Designer.m
> +                study = obj.model.CreateStudy('Transient', studyName);
The JMAG `study` needs to be created for assigning materials, and we need to specify the type of study (`Transient`, `Static`) when we are creating the study and this `studyType` cannot be changed later.
To solve this issue, I have added the ability for the user to define the `studyType` when calling the `JMAG_Designer` initializer using the key-value pair argument (varargin). Please refer to the `JMAG_Designer` initializer method for more information.

2021-04-18 17:56 UTC, ASHAD1 commented
I have updated the code that will resolve the issues (raised by @elsevers).

- Geometry Editor application will now be closed as the `close()` function is now calling `delete()` function which will close both JMAG Designer and Geometry Editor applications.
- The current implementation solves the issue of multiple model creation.
- I have updated the function comments as per the guidelines
- The JMAG `study` needs to be created for assigning materials, and we need to specify the type of study (`Transient`, `Static`) when we are creating the study and this cannot be changed later.
To solve this issue, I have added the ability for the user to define the `studyType` when calling the `JMAG_Designer` initializer using the key-value pair argument (varargin). Please refer to the `JMAG_Designer` initializer method for more information.

2021-04-20 15:47 UTC, Bharat-Ramadas commented on tools/jmag/JMAG_Designer.m
> +            end
Do you need this for loop for assigning a value to the `studyType `property? It seems to me that `obj.createProps` will take care of this.

2021-04-20 15:58 UTC, Bharat-Ramadas reviewed
Looks good. I just have one comment on the initializer. Please find it below

2021-04-20 21:37 UTC, Bharat-Ramadas approved these changes
Looks good

2021-05-09 00:21 UTC, Bharat-Ramadas submitted a review, later dismissed
Looks good

2021-05-26 00:56 UTC, elsevers requested changes
This is looking pretty good. However, I seem to have found a problem.

If I run `exampleBreadLoaf.m` , a JMAG project file is created `test_breadLoaf.jproj` and JMAG closes. If I then try to open this JMAG file by running this command `toolJD = JMAG_Designer('test_breadLoaf.jproj')`, I get this prompt:

![image](https://user-images.githubusercontent.com/7421348/119586916-3d3a3880-bd93-11eb-9d14-af76276a33b7.png)

Seems like a bug...

2021-05-26 18:42 UTC, ngadiyar93 commented
> This is looking pretty good. However, I seem to have found a problem.
> 
> If I run `exampleBreadLoaf.m` , a JMAG project file is created `test_breadLoaf.jproj` and JMAG closes. If I then try to open this JMAG file by running this command `toolJD = JMAG_Designer('test_breadLoaf.jproj')`, I get this prompt:
> 
> ![image](https://user-images.githubusercontent.com/7421348/119586916-3d3a3880-bd93-11eb-9d14-af76276a33b7.png)
> 
> Seems like a bug...

@elsevers I faced this error when i was running `exampleBreadLoaf.m` with my MATLAB path being on a Google Drive file stream location (This is where i had cloned eMach). 

However, it runs fine if I run it with a MATLAB path that is on my disk. I also checked if the issue is due to spaces in any of the location names in the file path, but that doesn't seem to be an issue.

So to verify if this is indeed the issue, could you change line 116 in `exampleBreadLoaf.m`  to something like `path = C:\Users\username\Documents` and run it to see if JMAG still shows the same error in saving the file?

2021-05-26 20:10 UTC, elsevers commented
> 
> 
> > This is looking pretty good. However, I seem to have found a problem.
> > If I run `exampleBreadLoaf.m` , a JMAG project file is created `test_breadLoaf.jproj` and JMAG closes. If I then try to open this JMAG file by running this command `toolJD = JMAG_Designer('test_breadLoaf.jproj')`, I get this prompt:
> > ![image](https://user-images.githubusercontent.com/7421348/119586916-3d3a3880-bd93-11eb-9d14-af76276a33b7.png)
> > Seems like a bug...
> 
> @elsevers I faced this error when i was running `exampleBreadLoaf.m` with my MATLAB path being on a Google Drive file stream location (This is where i had cloned eMach).
> 
> However, it runs fine if I run it with a MATLAB path that is on my disk. I also checked if the issue is due to spaces in any of the location names in the file path, but that doesn't seem to be an issue.
> 
> So to verify if this is indeed the issue, could you change line 116 in `exampleBreadLoaf.m` to something like `path = C:\Users\username\Documents` or any other path on your disk and run it to see if JMAG still shows the same error in saving the file?

This error is because I am not passing in the full path of the file location. However, this exposes a problem in your `open` function. If I give it a name of a file that does not exist, it should be trying to create that file. Instead, it is calling `obj.jd.Load()` on this non-existent file

2021-05-26 20:16 UTC, ngadiyar93 commented
> > > This is looking pretty good. However, I seem to have found a problem.
> > > If I run `exampleBreadLoaf.m` , a JMAG project file is created `test_breadLoaf.jproj` and JMAG closes. If I then try to open this JMAG file by running this command `toolJD = JMAG_Designer('test_breadLoaf.jproj')`, I get this prompt:
> > > ![image](https://user-images.githubusercontent.com/7421348/119586916-3d3a3880-bd93-11eb-9d14-af76276a33b7.png)
> > > Seems like a bug...
> > 
> > 
> > @elsevers I faced this error when i was running `exampleBreadLoaf.m` with my MATLAB path being on a Google Drive file stream location (This is where i had cloned eMach).
> > However, it runs fine if I run it with a MATLAB path that is on my disk. I also checked if the issue is due to spaces in any of the location names in the file path, but that doesn't seem to be an issue.
> > So to verify if this is indeed the issue, could you change line 116 in `exampleBreadLoaf.m` to something like `path = C:\Users\username\Documents` or any other path on your disk and run it to see if JMAG still shows the same error in saving the file?
> 
> This error is because I am not passing in the full path of the file location. However, this exposes a problem in your `open` function. If I give it a name of a file that does not exist, it should be trying to create that file. Instead, it is calling `obj.jd.Load()` on this non-existent file

@elsevers If you specify the full file path as the fileName (which is what the JMAG tool looks for), even if such a file is non existent, JMAG creates it. 
![image](https://user-images.githubusercontent.com/43225038/119724937-f69d1a80-be34-11eb-83e3-b07e12f8d8a6.png)
The problem is when one only specifies a file name.

For example:
`toolJd = JMAG_Designer('C:\Users\username\Documents\JMAG test\test.jproj');` works and will create a `test.jproj` if it doesn't already exist.
However, `toolJd = JMAG_Designer('test.jproj');` does not work.

I am not sure this is a bug as we are specifying that the user has to input the full file path?

2021-05-26 20:30 UTC, elsevers commented
It looks like your issue can be resolved by adding this at the start of the function:

```matlab
fileName = which(fileName);
```

Be careful about your error checking for `~exist('fileName', 'var')`

2021-05-26 20:43 UTC, elsevers commented
I see you have added my suggestion to your constructor. However, it belongs in your `open` function, not the constructor.

2021-05-26 21:42 UTC, ASHAD1 commented
@elsevers I have implemented the changes you have requested in the latest commits.

2021-05-26 22:07 UTC, elsevers commented
> 
> 
> @elsevers I have implemented the changes you have requested in the latest commits.

@ASHAD1, your changes break the case of creating a new project. Try running `exampleBreadloaf.m`. It does not work.

2021-05-26 23:11 UTC, ASHAD1 commented
@elsevers Thanks for pointing this out. I have fixed this issue. I have verified it by running the example files.

Also in the latest commits, for the case where the file name without the full file path is used (ex. `'test2.jproj'`), and if this file (`test2.jproj`) is not present in the current folder, then a new file will be created in the current folder. Please let me know if you want a different approach.

2021-05-28 13:57 UTC, elsevers requested changes
Getting closer. Now the functionality just described works. However, now the tool is unable to open a project that is not on the MATLAB path. 

To re-create this issue, perform the following steps:

1. Setup your MATLAB path to include all the eMach project folders except `examples`. When your MATLAB working directory is set to the eMach folder, if your MATLAB path is configured correctly, the `examples` directory should be gray while the others are solid, like this screen shot: 
![image](https://user-images.githubusercontent.com/7421348/119995345-1a767280-bf93-11eb-85bf-a270ed318d14.png)

2. Set your working directory to be the `eMach\examples` folder and run `exampleBreadloaf.m`. This will create `test_breadLoaf.jproj`
3. Now set your working directory to be `eMach` (no longer in the examples folder) and try to open `test_breadLoaf.jproj` by running this command (modify your path appropriately)
```matlab
toolJD = JMAG_Designer('D:\WorkingCopies\eMach\examples\test_breadLoaf.jproj')
```
It will fail (but it should work!). You should also be able to open the file by providing a path relative to your working directory. I.e., this command should work as well (but does not)

```matlab
toolJD = JMAG_Designer('examples\test_breadLoaf.jproj')
```

Please fix the tool so that both work.

2021-05-28 22:01 UTC, ASHAD1 commented
@elsevers I have fixed the issue in the latest commit.

2021-05-28 22:11 UTC, elsevers approved these changes
Looks good @ASHAD1! 

Momentous occasion: this PR is **approved**. Thanks for all of your efforts on this.

2021-05-28 22:15 UTC, Bharat-Ramadas approved these changes
🥂

2021-05-28 22:15 UTC, merged