Add markdown documentation for python-MAGNET interfacing
Severson-Group/eMach-matlab pull request #142
Opened 2020-11-13 13:47 UTC by Bharat-Ramadas

2020-11-13 15:00 UTC, ngadiyar93 requested changes
Nice work Bharat. Please see my comments.

2020-11-13 15:00 UTC, ngadiyar93 commented on python/tools/magnet/emach/README.md
> +- In order for Python to communicate with MAGNET, we need to import the pywin32 to call ActiveX compliant programs as COM automation servers. The pywin32 module comes with Anaconda3 installation and
@Bharat-Ramadas Probably changing sentences to third person makes it more consistent with rest of the documentation in eMach?
i.e, changing `In order for Python to communicate with MAGNET, we need to import the pywin32 to call ActiveX compliant programs as COM automation servers`  to `In order for Python to communicate with MAGNET, the pywin32 needs to be imported to call ActiveX compliant programs as COM automation servers` or equivalent

The current documentation in eMach for Matlab has this style: https://github.com/Severson-Group/eMach/blob/develop/README.md

2020-11-13 15:16 UTC, Bharat-Ramadas commented on python/tools/magnet/emach/README.md
> +- In order for Python to communicate with MAGNET, we need to import the pywin32 to call ActiveX compliant programs as COM automation servers. The pywin32 module comes with Anaconda3 installation and
@ngadiyar93 Thanks for the feedback! I'll update the markdown to more closely match the example you've shared.

2020-11-13 21:26 UTC, Bharat-Ramadas commented on python/tools/magnet/emach/README.md
> +- In order for Python to communicate with MAGNET, we need to import the pywin32 to call ActiveX compliant programs as COM automation servers. The pywin32 module comes with Anaconda3 installation and
@ngadiyar93 Please check the updated file and let me know your thoughts on the same.

2020-11-20 01:45 UTC, ngadiyar93 requested changes
Nice Work Bharat!. Please see my comments.

2020-11-20 01:45 UTC, ngadiyar93 commented on python/tools/magnet/emach/README.md
> +- In order for python to communicate with MAGNET, the pywin32 module has to be imported to call ActiveX compliant programs as Component Object Model (COM) automation servers. The pywin32 module comes
Where do I run this command- `from win32com.client import DispatchEx`?
Should the user run this in Anaconda Prompt? Or should this be added to the first line of the script? Or does it work either way?
May be a good idea to make it explicit?.

2020-11-20 01:45 UTC, ngadiyar93 commented on python/tools/magnet/emach/README.md
> +- If the importing of the module raises an error flag, please make sure that the path of the Anaconda3 site-packages has been added to the system's `Environment variables` as `PYTHONPATH`.
May be better to say `If an error occurs and the module import is unsuccessful, please make sure.......` ?

2020-11-20 01:45 UTC, ngadiyar93 commented on python/tools/magnet/emach/README.md
> +- Functions who's return values can be directly accessed by assigining the function call to a variable fall under the first category. `makeSimpleCoil` is an example of such a function. Its return val
I guess you mean to say "whose" and not "who's" ?

2020-11-20 01:45 UTC, ngadiyar93 commented on python/tools/magnet/emach/README.md
> +The function definition of MAGNET APIs can be obtained from MAGNET's Help Topics.
@Bharat-Ramadas Do you think the MagNet knowledgebase article with the Python scripting example would be useful? If so, could you also add a link to it?

2020-11-20 17:29 UTC, elsevers requested changes
- [x] Clean up grammar and some capitalization (`Python` and `MagNet`)
- [ ] Provide more narrative framing to make this an easier read at the start of each section
- [ ] Revise purpose statement to clarify that this doc is intended for developers and make the language more direct.

2020-11-20 17:32 UTC, elsevers commented
Why is this in an `emach` subfolder? We don't want to have a folder in the repo called `emach`

2020-12-04 16:58 UTC, elsevers approved these changes

2020-12-05 00:20 UTC, ngadiyar93 approved these changes
Looks good to me!

2020-12-20 18:00 UTC, merged