Add crosssect documentation
Severson-Group/eMach-matlab pull request #143
Opened 2020-11-20 01:29 UTC by ngadiyar93

This PR adds documentation containing instructions to add new crosssects.

2020-11-20 16:12 UTC, Bharat-Ramadas submitted a review, later dismissed
Looks good @ngadiyar93 !

2020-11-20 17:13 UTC, elsevers requested changes
Please add missing periods and colons.

2020-12-03 15:34 UTC, ngadiyar93 commented
@elsevers, @Bharat-Ramadas @aimthiazz @ASHAD1  I have updated the markdown document. It can be reviewed.

2021-02-11 21:09 UTC, elsevers requested changes
Please add example of a cross-section drawing that is compliant with these guidelines

2021-02-23 22:01 UTC, Bharat-Ramadas commented on model_obj/crosssects/README.md
> +The `Crosssect` class implements cross-sections of standard geometry shapes that are usually encountered when using eMach. This document specifies the rules to be followed to add a new cross-section
It might be better to say "... shapes that are usually encountered in machine design..." rather than "eMach"

2021-02-23 22:08 UTC, ngadiyar93 commented on model_obj/crosssects/README.md
> +The `Crosssect` class implements cross-sections of standard geometry shapes that are usually encountered when using eMach. This document specifies the rules to be followed to add a new cross-section
@Bharat-Ramadas thank you!. Fixed this now.

2021-02-23 22:11 UTC, Bharat-Ramadas submitted a review, later dismissed
Nice work!

2021-02-25 02:31 UTC, aimthiazz approved these changes, later dismissed
Looks good.

2021-02-25 02:51 UTC, aimthiazz approved these changes
Looks good!!

2021-02-25 18:33 UTC, elsevers approved these changes

2021-02-25 18:35 UTC, merged