Add function signatures to abstract base methods
Severson-Group/eMach-matlab pull request #149
Opened 2020-12-04 15:29 UTC by Bharat-Ramadas

# Description

This PR addresses issue #146. All abstract class methods now have the expected function signatures

2020-12-04 17:14 UTC, elsevers requested changes
Need to provide type hints in the function signatures.

2021-02-11 22:00 UTC, elsevers requested changes
See detailed comments. Need to create `TokenDraw` class.

2021-02-11 22:00 UTC, elsevers commented on python/emach/tools/tool_abc/toolabc.py
> +    def open(self, filename: str, visible: bool) -> None: pass
Don't specify return value on `open`

2021-02-11 22:00 UTC, elsevers commented on python/emach/tools/tool_abc/toolabc.py
> +    def draw_line(self, startxy: Location2D, endxy: Location2D) -> int: pass
`draw_line` should return a `TokenDraw` object (need to create `TokenDraw` class)

2021-02-11 22:00 UTC, elsevers commented on python/emach/tools/tool_abc/toolabc.py
> +    def draw_arc(self, centerxy: Location2D, startxy: Location2D,
`draw_arc` should return a `TokenDraw` object (need to create `TokenDraw` class)

2021-02-11 22:00 UTC, elsevers commented on python/emach/tools/tool_abc/toolabc.py
> +    def prepare_section(self, inner_coord: Location2D) -> None: pass
Don't specify return value on this function

2021-02-11 22:00 UTC, elsevers commented on python/emach/tools/tool_abc/toolabc.py
> +    def extrude(self, name: List[str], material: str, depth: float, token) -> int: pass
Don't specify return value on this function

2021-02-11 22:00 UTC, elsevers commented on python/emach/tools/tool_abc/toolabc.py
> +    def revolve(self, name: List[str], material: str, center: Location2D,
Don't specify return value on this function

2021-02-24 02:21 UTC, aimthiazz submitted a review, later dismissed
Looks good - Indicated comments have been addressed.

2021-02-25 02:52 UTC, ngadiyar93 submitted a review, later dismissed

2021-02-25 18:43 UTC, mwjohnson56 approved these changes, later dismissed
All function signatures have been added to this class.

2021-02-25 21:57 UTC, elsevers approved these changes

2021-02-25 21:57 UTC, ngadiyar93 approved these changes

2021-02-25 21:58 UTC, aimthiazz approved these changes

2021-02-25 21:58 UTC, merged