Add python support for Dimensions
Severson-Group/eMach-matlab pull request #150
Opened 2020-12-11 08:24 UTC by aimthiazz

Issue #139 
- [x] Protected to_dimes and from_dimes
- [x] Change name for to_dimes and from_dimes
- [x] Take advantage of polymorphism to have complete to_dimes and from_dimes functions defined in your abstract base class DimLinear

2020-12-21 15:37 UTC, elsevers requested changes
Please change: 

- [x] DimLinear.py misspells `_to_dimesionless` and `_from_dimesionless`
- [x] DimLinear/DimLinear should return a scalar
- [ ] Need to move `_to_dimensionless` and `_from_dimensionless` to the abstract base class. Recommended implementation: use an abstract conversion_factor property in these functions that the child classes must implement

2021-01-22 17:58 UTC, Bharat-Ramadas commented on python/model_obj/Dimensions/dim_linear.py
> +    @abstractmethod
Are these functions supposed to be `abstractmethods`?

2021-01-22 18:00 UTC, Bharat-Ramadas commented on python/model_obj/Dimensions/main.py
> +from dim_millimeter import DimMillimeter
I think it would be better to have the `main.py` file in the `examples `folder

2021-01-22 18:04 UTC, Bharat-Ramadas commented on python/model_obj/Dimensions/dim_angular.py
> +from dim_base import DimBase
Please change the `model_obj` location to be within the `emach` module

2021-02-01 20:51 UTC, aimthiazz commented on python/model_obj/Dimensions/dim_angular.py
> +from dim_base import DimBase
Moved to `model_obj` location

2021-02-01 20:51 UTC, aimthiazz commented on python/model_obj/Dimensions/main.py
> +from dim_millimeter import DimMillimeter
Moved to `examples`  folder

2021-02-01 20:54 UTC, aimthiazz commented on python/model_obj/Dimensions/dim_linear.py
> +    @abstractmethod
Since ` to_millimeter()` and `to_inch()` are abstract method, I kept `_to_dimensionsless()` and `_from_dimensionless()` as abstractmethod.

2021-02-10 20:17 UTC, Bharat-Ramadas approved these changes, later dismissed
Looks good to me.

2021-02-11 04:56 UTC, aimthiazz commented on python/emach/model_obj/Dimensions/dim_angular.py
> +    def __neg__(self):
#160 Addressed

2021-02-18 15:57 UTC, mwjohnson56 approved these changes, later dismissed
Everything looks good here are ready to merge. I tested the code and it worked on my system. I have one small addition that I would like to be added as a new issue which is to utilize the `__repr__()` and `__str__()` functions to have the Dimensions objects output their units when displayed in the console or printed. See following code for the `DimInch` object.

` def __str__(self):
         return self.__repr__() `
`def __repr__(self):
        return float.__repr__(self) + ' [in]' `

2021-02-25 18:42 UTC, elsevers commented on python/emach/examples/example_dimension_unit_test.py
> +# add the directory immediately above this file's directory to path for module import
@aimthiazz I get a path error when trying to run this file.  Is this expected? How can I fix it?

![image](https://user-images.githubusercontent.com/7421348/109200956-d3e06480-7766-11eb-9111-4f6f6f5a0afb.png)

2021-02-25 18:59 UTC, elsevers requested changes

2021-02-25 18:59 UTC, elsevers commented on python/emach/model_obj/Dimensions/dim_base.py
> +
It seems to me that `DimBase` should have house these methods:

```python
    @property
    @abstractmethod
    def conversion_factor(self):
        pass
        
    @abstractmethod
    def _to_dimensionless(self):
        return float(self.data*self.conversion_factor)

    @abstractmethod    
    def _from_dimensionless(self):
        x = self.result/self.conversion_factor
        return self.__class__(x)
```

Do `_from_dimensionless` and `_to_dimensionless` need to be abstract or can they be concrete at the base class level?

2021-02-25 18:59 UTC, elsevers commented on python/emach/model_obj/Dimensions/dim_linear.py
> +        return self.__class__(x)
I am confused about these functions being decorated with `@abstractmethod`. I would expect that this means that the classes inheriting `dim_linear` need to implement these methods. However, I can see that `dim_inch` and `dim_millimeter` do not implement these methods.  Rather, the methods appear to be fully defined here in `dim_linear`.

Can you explain?

2021-02-25 18:59 UTC, elsevers commented on python/emach/model_obj/Dimensions/dim_linear.py
> +        pass
`dim_millimeter` and `dim_inch` appear to be implementing `to_mm` and not `to_millimeter`...

2021-02-25 18:59 UTC, elsevers commented on python/emach/model_obj/Dimensions/dim_linear.py
> +        pass
Do we have any need for these `to_inch` and `to_millimeter` functions any more?

2021-02-25 22:06 UTC, elsevers commented
Let's remove the functions

`to_inch`
`to_millimeter` (and `to_mm`)
`to_degree`
`to_radian`

This was an old way of thinking and we are doing better now by using the to/from dimensionless approach

2021-02-26 23:14 UTC, Bharat-Ramadas commented on python/emach/model_obj/Dimensions/dim_linear.py
> +class DimLinear(DimBase, ABC):
Does `DimLinear `need to inherit `ABC`?

2021-02-26 23:15 UTC, Bharat-Ramadas commented on python/emach/model_obj/Dimensions/dim_degree.py
> +        return 3.14/180
Its might be better to use `np.pi` here instead of 3.14

2021-02-26 23:20 UTC, Bharat-Ramadas commented on python/emach/examples/example_dimension_unit_test.py
> +# add the directory immediately above this file's directory to path for module import
This error is happening because of a weird Git quirk. Git does not recognize the change in the naming of the `dimensions` module from `Dimensions` to `dimensions` (first letter case change). However, Python is case sensitive and sees `Dimensions` and `dimensions` as different modules. You can fix this error by simply renaming the `Dimensions` folder within `model_obj` to `dimensions`.

2021-02-27 00:25 UTC, aimthiazz commented on python/emach/model_obj/Dimensions/dim_degree.py
> +        return 3.14/180
I wanted to avoid importing the NumPy model just for this file. I am circumventing the issue by increasing the significant digits of pi, i.e, Using `3.14159265359` instead of `3.14`

2021-02-27 00:33 UTC, aimthiazz commented on python/emach/examples/example_dimension_unit_test.py
> +# add the directory immediately above this file's directory to path for module import
I resolved this issue by renaming the folder from `dimensions` to `dimension`, then back to `dimensions`.  Git has recognized this and changed the folder name to `dimensions` instead of `Dimensions`

2021-02-27 00:46 UTC, Bharat-Ramadas approved these changes
Looks good!

2021-03-02 03:22 UTC, mwjohnson56 approved these changes
Everything looks good, the required changes to the `dim_angular`, `dim_radian` and `dim_degree` have all been implemented in the same style as the `dim_linear` classes.

2021-03-06 03:40 UTC, elsevers requested changes
Thanks @aimthiazz. Looks good!

See my detailed comments. My primary comment is that the unary operations of `DimLinear` could just as well apply to any dimension and so they should reside in the base class `DimBase`

2021-03-06 03:40 UTC, elsevers commented on python/emach/model_obj/dimensions/dim_linear.py
> +        if isinstance(self, DimLinear):
Is this check necessary? (Doesn't self have to be of type `DimLinear` since it is in the `DimLinear` class?

I also don't like it because this check implies that there is a path through this function that returns nothing (i.e., if somehow the object type is not an instance of `DimLinear` [which is impossible])

2021-03-06 03:40 UTC, elsevers commented on python/emach/model_obj/dimensions/dim_linear.py
> +    def __add__(self, other):
I think we should actually just move all of these unary operations from `DimLinear` to `DimBase` so that they will work for angular as well as linear dimensions.

2021-03-06 13:44 UTC, elsevers approved these changes
I am going to turn my revision requests into an issue and approve this code as-is, as it does implement the original request successfully. Nice job.

2021-03-06 13:44 UTC, merged