Add hollow cylinder cross-section drawing capability and all supporting files
Severson-Group/eMach-matlab pull request #159
Opened 2020-12-21 12:22 UTC by Bharat-Ramadas

# Description

This PR adds all the functionality necessary for drawing cross-sections in python. This include `Location2D`, `CrossSectBase` and `CrossSectToken`, `HollowCylinder` class has been implemented and an example associated with the same as well.

# Related Issues
#140  #141

2021-02-25 03:23 UTC, aimthiazz approved these changes, later dismissed

2021-02-25 18:56 UTC, ASHAD1 commented on python/emach/model_obj/cross_sects.py
> +# -*- coding: utf-8 -*-
I think we need to use separate cross_section files for every component. So this should be renamed something like `cross_sect_hollow_cylinder.py`

2021-03-07 02:18 UTC, ngadiyar93 commented on python/emach/examples/example_hollow_cylinder_cross.py
> +Created on Fri Nov 13 01:02:08 2020
Minor comment: I am not a Python expert and unsure if we need all of these comments with date, author name etc? Maybe we want to keep it consistent with the Matlab style and not have any of that?

I know Spyder puts this in by default but it can be [changed](https://stackoverflow.com/questions/47619939/how-to-change-the-default-module-docstring-in-spyder).

2021-03-07 02:18 UTC, ngadiyar93 commented on python/emach/model_obj/__init__.py
Same comment about the date / author info.

2021-03-07 02:18 UTC, ngadiyar93 commented on python/emach/model_obj/cross_sects/cross_sect_base.py
> +
Same comment about the date / author info.

2021-03-07 02:18 UTC, ngadiyar93 commented on python/emach/model_obj/cross_sects/cross_sect_hollow_cylinder/__init__.py
> +
Same comment about the date / author info.

2021-03-07 02:21 UTC, ngadiyar93 commented on python/emach/model_obj/cross_sects/cross_sect_hollow_cylinder/README.md
> +<img src="./CrossSectHollowCylinder.svg" width="500" height="500" />
There seems to be some issue with the line color / fill color for the label `d_a`

2021-03-08 04:54 UTC, aimthiazz approved these changes, later dismissed
Works on my PC.  Approved.

2021-03-08 15:04 UTC, ngadiyar93 submitted a review, later dismissed

2021-03-20 21:14 UTC, aimthiazz submitted a review, later dismissed

2021-03-21 01:24 UTC, elsevers requested changes
Thanks @Bharat-Ramadas -- I think this is looking pretty good. I have a few requests entered in below. Also, I have this question / request that I have also put into slack:

> Tell me about the folder name `cross_sect_hollow_cylinder` -- it seems quite redundant to have `crosssects\cross_sect_xxxx`. Can you propose something to remove some of the redundancy?

2021-03-21 01:24 UTC, elsevers commented on python/emach/model_obj/cross_sects/cross_sect_base.py
> +class CrossSectBase(ABC):
This class is missing the properties `name` and `location` as well as the method `clone()` that are provided in the MATLAB implementation. Is there a reason for not providing these in the abstract base class or where they just forgotten (in which case, please add)?

2021-03-21 01:24 UTC, elsevers commented on python/emach/model_obj/cross_sects/cross_sect_hollow_cylinder/__init__.py
> +        self.__location = location;
In the MATLAB implementation `__name` and `__location` reside in the abstract base class. Seems like we should do the same here because that is part of the contract that a cross_sect must fulfill

2021-03-21 01:24 UTC, elsevers commented on python/emach/model_obj/cross_sects/cross_sect_hollow_cylinder/__init__.py
> +    def __init__(self, name: str, dim_t: 'DimLinear', dim_r_o: 'DimLinear', \
I see that your initializer has each dimension listed explicitly as an argument. The seems reasonable for simple geometry, like the hollow cylinder, but not great for complex geometry where there are a low of parameters (i.e. [inner rotor stator](https://github.com/Severson-Group/eMach/tree/develop/model_obj/crosssects/innerRotorStator)).  

In MATLAB, we used `varargin` to address this, and then accepted key value pairs, like a dictionary. 

What is the best practice for python? Is there style guidance on how to avoid absurdly length lists of arguments in class initializers and functions?

2021-03-21 04:32 UTC, Bharat-Ramadas commented on python/emach/model_obj/cross_sects/cross_sect_hollow_cylinder/__init__.py
> +    def __init__(self, name: str, dim_t: 'DimLinear', dim_r_o: 'DimLinear', \
In Python, the recommended approach is to use keyword arguments of `*kwargs`. By doing this, you can pass in a dictionary of arguments similar to Matlab. This [link](https://stackabuse.com/variable-length-arguments-in-python-with-args-and-kwargs/) provides more information on keyword arguments in python

2021-03-21 05:25 UTC, Bharat-Ramadas commented on python/emach/model_obj/cross_sects/cross_sect_hollow_cylinder/__init__.py
> +        self.__location = location;
In Python, we cannot define abstract properties, we can only define abstract methods. Specifying `name` and `location` as abstract methods might cause confusion which is why I decided not to place them within the abstract base class

2021-03-21 05:30 UTC, Bharat-Ramadas commented on python/emach/model_obj/cross_sects/cross_sect_base.py
> +class CrossSectBase(ABC):
In Python, we cannot define abstract properties, we can only define abstract methods. Specifying name and location as abstract methods might cause confusion which is why I decided not to place them within the abstract base class. `clone( )` is something I forgot to implement, so I'll work on that.

2021-03-21 12:23 UTC, elsevers commented on python/emach/model_obj/cross_sects/cross_sect_hollow_cylinder/__init__.py
> +        self.__location = location;
@Bharat-Ramadas in this case, these properties do not need to be abstract. They are repeated functionality which we want to guarantee that every class which inherits the base class has. Sure seems to me that they belong in the base class. Is it possible to make use of the base class initializer to ensure they are always set up properly?

2021-03-21 12:23 UTC, elsevers commented on python/emach/model_obj/cross_sects/cross_sect_hollow_cylinder/__init__.py
> +    def __init__(self, name: str, dim_t: 'DimLinear', dim_r_o: 'DimLinear', \
Great. Do it!

2021-03-21 13:10 UTC, elsevers commented on python/emach/model_obj/cross_sects/cross_sect_hollow_cylinder/__init__.py
> +    def __init__(self, name: str, dim_t: 'DimLinear', dim_r_o: 'DimLinear', \
Looks like if you are going to do this, you should also bring over the property validation architecture that the MATLAB cross-sects use. (`validateProps` and `createProps`)

2021-03-24 02:51 UTC, Bharat-Ramadas commented on python/emach/model_obj/cross_sects/cross_sect_hollow_cylinder/__init__.py
> +    def __init__(self, name: str, dim_t: 'DimLinear', dim_r_o: 'DimLinear', \
I've implemented both `validateProps `and `createProps `(`_create_attr ` and `_validate_attr `in Python)

2021-03-24 02:56 UTC, Bharat-Ramadas commented on python/emach/model_obj/cross_sects/cross_sect_hollow_cylinder/__init__.py
> +        self.__location = location;
I've implemented the validateProps Matlab equivalent of `name` and `location` in `cross_sect_base`. `createProps` has now been moved to reside in the base class as it seems that the same function is repeated in each `cross_sect`

2021-03-24 22:33 UTC, aimthiazz approved these changes, later dismissed
Works on my PC. Looks good.

2021-03-25 04:27 UTC, ASHAD1 commented on python/emach/examples/example_hollow_cylinder_cross.py
> +                                                dim_t = x, dim_r_o = y)
Looks like in this example you are not extruding and assigning materials, do we need this in this example?

2021-03-25 04:43 UTC, Bharat-Ramadas commented on python/emach/examples/example_hollow_cylinder_cross.py
> +                                                dim_t = x, dim_r_o = y)
@ASHAD1 Yeah, that will come after we implement `eMach` `components`. Right now, this is just to test the cross-sect functionality. We haven't gotten to that point yet in the python implementation.

2021-03-25 17:11 UTC, ASHAD1 commented on python/emach/examples/example_hollow_cylinder_cross.py
> +                                                dim_t = x, dim_r_o = y)
Okay, I see now. It's drawing the cross-section, not components. I will go through this PR in detail again. Thanks.

2021-03-31 17:27 UTC, aimthiazz submitted a review, later dismissed

2021-04-01 00:37 UTC, elsevers requested changes
Looks great! I have two small change requests (see my comments on your code). Address these, and I'll approve this.

2021-04-01 00:37 UTC, elsevers commented on python/emach/model_obj/cross_sects/hollow_cylinder/__init__.py
> +        return self._location
It seems to me that `name` and `location` belong in the base class to make your code DRY because all cross sects have these properties.

2021-04-01 00:37 UTC, elsevers commented on python/emach/model_obj/location_2d.py
> +    def trans_coord(self, coords, add_theta = None):
Please name this function `transform_coords`

2021-04-01 04:24 UTC, Bharat-Ramadas commented on python/emach/model_obj/cross_sects/hollow_cylinder/__init__.py
> +        return self._location
Done!

2021-04-01 04:24 UTC, Bharat-Ramadas commented on python/emach/model_obj/location_2d.py
> +    def trans_coord(self, coords, add_theta = None):
Sure thing

2021-04-01 04:33 UTC, aimthiazz approved these changes

2021-04-01 17:28 UTC, elsevers approved these changes
Looks good. Thanks @Bharat-Ramadas

2021-04-01 19:47 UTC, merged