Add TokenDraw Class
Severson-Group/eMach-matlab pull request #166
Opened 2021-02-21 22:25 UTC by Bharat-Ramadas

# Description
This PR adds the `TokenDraw ` class and supporting changes in the magnet tool module.

# Related Issues
#165

2021-02-25 02:36 UTC, aimthiazz commented on python/emach/tools/token_draw.py
> +    def __init__(self, segment_indices: any, segment_type: int) -> None :
typehint `->any`

2021-02-25 02:43 UTC, aimthiazz submitted a review, later dismissed
Looks good.

2021-02-25 18:35 UTC, ngadiyar93 approved these changes, later dismissed
Looks good to me.

2021-02-25 22:15 UTC, elsevers requested changes

2021-02-25 22:15 UTC, elsevers commented on python/emach/tools/token_draw.py
> +        self.segment_type = segment_type
Please match variable names to the MATLAB code.

2021-02-25 22:15 UTC, elsevers commented on python/emach/tools/token_draw.py
> +
Make properties read only

2021-02-26 00:12 UTC, aimthiazz submitted a review, later dismissed

2021-02-26 01:11 UTC, elsevers requested changes

2021-02-26 01:11 UTC, elsevers commented on python/emach/tools/token_draw.py
> +        '''
There parameter names in this comment block do not match the arguments in your initializer. 

Also, is it true that an initializer returns nothing? It seems to me that it returns a `TokenDraw` object.

Finally, why is there so much vertical white space in this comment block? Are you following a certain Python style, or is this a mistake?

2021-02-26 05:04 UTC, Bharat-Ramadas commented on python/emach/tools/token_draw.py
> +        '''
The docustring has been revised to reflect the function arguments

The initializer does not return anything in Python. It is the constructor that returns the instance of the class ( `__new__` ). Most of the time the constructor does not have to be explicitly declared in Python (however, we have made use of `__new__` in the implementation of dimensions).

The functions docstrings outline gets generated automatically when using Spyder. I used this as the default documentation and made changes on top of it where required. This resulted in the large vertical while space in the comment. Some of the vertical space was provided for descriptions and other are to segregate between different sections of the docustring. I looked up some examples and [PEP257](https://www.python.org/dev/peps/pep-0257/) found that there is no style specification on vertical white space.

2021-03-06 14:17 UTC, elsevers requested changes
@Bharat-Ramadas your implementation of `TokenDraw` looks good to me, but I am confused about your changes to `magnet.py`. Why are you removing the tokens on extrude and revolve? This doesn't match the MATLAB eMach implementation.

2021-03-06 14:17 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
> +    def extrude(self, name, material, depth):
Why are you removing the token from this function signature? 

All classes implementing `MakerExtrudeBase` need to be able to receive a token here

2021-03-06 14:17 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
> +    def revolve(self, name, material, center, axis, angle):
Why is `token` being removed here? This does not match the MATLAB implementation

2021-03-06 18:26 UTC, Bharat-Ramadas commented on python/emach/tools/magnet/magnet.py
> +    def extrude(self, name, material, depth):
In our last meeting, the point was raised that `token` should be removed from both the Matlab and Python implementation. Even though the Matlab function has an argument `token`, it is not used anywhere within the function. Also, the function signature provided in the base class `MakerExtrudeBase` (Matlab) does not include `token`
https://github.com/Severson-Group/eMach/blob/f8bd845a7275ece4f4618324923e5ff66876eb77/tools/makerBase/MakerExtrudeBase.m#L12

2021-03-06 18:27 UTC, Bharat-Ramadas commented on python/emach/tools/magnet/magnet.py
> +    def revolve(self, name, material, center, axis, angle):
In our last meeting, the point was raised that `token` should be removed from both the Matlab and Python implementation. Even though the Matlab function has an argument `token`, it is not used anywhere within the function. Also, the function signature provided in the base class `MakerRevolveBase` (Matlab) does not include `token`
https://github.com/Severson-Group/eMach/blob/f8bd845a7275ece4f4618324923e5ff66876eb77/tools/makerBase/MakerRevolveBase.m#L13

2021-03-06 19:24 UTC, elsevers requested changes

2021-03-06 19:24 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
> +    def extrude(self, name, material, depth):
@Bharat-Ramadas, I don't remember this being the outcome of that discussion. Is there a PR or issue you can point me to that will refresh my memory?

These tokens are not actually used by MagNet / JMAG right now, but it is highly likely a future tool may require this information. To see why this is true, follow the flow of information in the `run()` function of `MakeExtrude.m` and `MakeRevolve.m`:

https://github.com/Severson-Group/eMach/blob/f8bd845a7275ece4f4618324923e5ff66876eb77/model_obj/makeSolid/MakeExtrude.m#L17-L34

Written in psuedocode, this looks like this:

```
1) csToken = drawer.drawTheCrossSection()
2) prepareToken = maker.prepareSection(csToken)
3) extrudeToken = maker.extrudeSection(prepareToken)

tokenMake = TokenMake(csToken, prepareToken, extrudeToken)
```
Do you see how `tokenMake` now contains all custom information generated my the tool (or maker)? This is returned to the eMach user when they call `tokenMake = component.make(drawer, maker)`. The user can then use this information for more advanced/custom interfacing to the tool. I.e., this is likely to be important to code that is actually solving for fields in the machine.

Make sense?

2021-03-07 05:57 UTC, Bharat-Ramadas commented on python/emach/tools/magnet/magnet.py
> +    def extrude(self, name, material, depth):
Yup, you've convinced me. I've reverted the functions back to their previous argument signature.

2021-03-07 19:40 UTC, aimthiazz submitted a review, later dismissed
Looks good

2021-03-07 19:45 UTC, ngadiyar93 reviewed
I have a comment that I have indicated. Else, looks good to me.

2021-03-07 19:45 UTC, ngadiyar93 commented on python/emach/tools/magnet/magnet.py
>  """
All the python files seem to have this header with author name, date created etc. Do we want to keep that? 
It seems to be an artifact from Spyder.....

2021-03-07 19:48 UTC, elsevers submitted a review, later dismissed
I am approving this based on `token_draw`. 

The MagNet tool class needs further work to be compliant with the latest spec of the MATLAB version: `prepare_section` should return a token, units of dimensions are not handled, and the type hints are needed.

2021-03-07 19:51 UTC, elsevers commented
I created issue #183 to track the improvements needed to the MagNet class

2021-03-07 19:51 UTC, elsevers approved these changes

2021-03-07 19:51 UTC, ngadiyar93 approved these changes

2021-03-07 19:52 UTC, merged