Fix Issue #173 , #174  and #175
Severson-Group/eMach-matlab pull request #176
Opened 2021-03-06 17:37 UTC by aimthiazz

This PR will address issues #173, #174, and #175.

2021-03-06 19:42 UTC, elsevers requested changes
@aimthiazz this seems to implement issue #174 and #175, but it does not fully implement #173.

`DimLinear` still contains functions that need to be moved to `DimBase` in order to implement #173:

```python
def __add__(self, other):
        add = self._to_dimensionless() + other._to_dimensionless()
        self.result = add
        return type(self)._from_dimensionless(self)

    def __sub__(self, other):
        sub = self._to_dimensionless() - other._to_dimensionless()
        self.result = sub
        return type(self)._from_dimensionless(self)

    def __mul__(self, other):
        if (isinstance(self, DimLinear) and isinstance(other, DimLinear)):
            raise Exception('Multiplication Not valid')

        else:
            mul = (other) * (self._to_dimensionless())
            self.result = mul 
            return type(self)._from_dimensionless(self)

    def __rmul__(self, other):
        if (isinstance(self, DimLinear) and isinstance(other, DimLinear)):
            raise Exception('Multiplication Not valid')

        else:
            mul = (other) * (self._to_dimensionless())
            self.result = mul
            return type(self)._from_dimensionless(self)


    def __truediv__(self, other):
        if (isinstance(other,DimLinear)):
            div = self._to_dimensionless() / other._to_dimensionless()
            return div
        else:
            div = (self._to_dimensionless()) / (other)
            self.result = div
            return type(self)._from_dimensionless(self)

    def __rtruediv__(self, other):
        raise Exception('Division not valid')

```

2021-03-14 17:43 UTC, Bharat-Ramadas submitted a review, later dismissed
The example runs as expected

2021-03-16 00:57 UTC, elsevers approved these changes
Looks good. Thanks @aimthiazz

2021-03-16 01:21 UTC, Bharat-Ramadas approved these changes

2021-03-16 02:25 UTC, merged