Update dimlinear child classes to address nested dimension issue
Severson-Group/eMach-matlab pull request #181
Opened 2021-03-06 23:40 UTC by aimthiazz

2021-03-08 02:07 UTC, Bharat-Ramadas submitted a review, later dismissed
Everything is working as expected on my PC. Good work @aimthiazz!

2021-03-11 21:34 UTC, elsevers requested changes

2021-03-11 21:34 UTC, elsevers commented on python/emach/model_obj/dimensions/dim_linear.py
> +        return type(self)._from_dimensionless(result)
This needs to be cleaned up

Implement `_from_dimensionless` as a class method in `DimBase` that takes in a type of object to create and then a dimensionless float

2021-03-26 00:09 UTC, Bharat-Ramadas reviewed
Looks great @aimthiazz! Just one minor comment that I have is to rename `conversion_factor` to `_conversion_factor` so that users know they are not supposed to access it.

2021-03-26 00:21 UTC, Bharat-Ramadas approved these changes, later dismissed
Looks good

2021-03-26 01:54 UTC, ngadiyar93 commented
@aimthiazz I haven't taken a close look at the changes, but it looks like you have few merge conflicts that need to be resolved.

2021-03-26 04:56 UTC, aimthiazz commented
Thanks, @ngadiyar93. I have resolved the confict.

2021-03-26 05:24 UTC, Bharat-Ramadas approved these changes

2021-04-01 00:38 UTC, elsevers approved these changes
Looks good!

2021-04-01 00:46 UTC, merged