Handle dimensions properly within MagNet tool
Severson-Group/eMach-matlab pull request #184
Opened 2021-03-08 06:35 UTC by Bharat-Ramadas

# Description
This PR implements the issue raised in #153. The `MagNet` tool now converts all `dimensions` to the default setting before passing the values on to the FEA software. 

# Problems Encountered
In order for the `MagNet` tool to access the dimensions classes such as `DimMillimeter` and `DimInch`, importing those classes from the corresponding module is necessary. `Python`, however does not allow a user to import modules that are at or above the directory where the execution file resides. Therefore, it became necessary to move the example folder to one level higher in order to get the code working.

2021-03-10 07:38 UTC, aimthiazz submitted a review, later dismissed
Ran Example, works in my PC

2021-03-20 01:29 UTC, elsevers requested changes

2021-03-20 01:29 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
> +        self.disp_ex.visible = visible
Why are you calling the magnet instance `disp_ex` and not `mn`. In MATLAB we use `mn` -- it seems like we should be using that same variable name here unless there is a reason not to.

2021-03-20 01:29 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
> +        self.default_angle = 'DimDegree'
Your initializer isn't allowing you to specify `default_length` and `default_angle` (the MATLAB version does allow this to be specified). I suggest you add them as function arguments here with default values.

2021-03-20 01:29 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
> +            self.doc.save(filepath)
The MATLAB implementation does not have an optional argument for saving upon closing. At our last eMach meeting we agreed that was the behavior we wanted. Please remove that functionality from here (remove lines 28 and 29).

2021-03-20 01:29 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
>          self.sol = self.doc.getSolution()
Interesting:
```python
self.sol = self.doc.getSolution()
```
I am unable to test this at the moment, but I am wondering -- does this cause an error if document does not have a solution? (I.e., this is a model that is not solved):
- *If it does throw an error,* we need to remove this
- *If it does not throw an error,* please add a review request on PR #186 for @ngadiyar93 to also get the solution.

2021-03-20 01:29 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
>          self.consts = self.disp_ex.getConstants()  # Get MAGNET Constants
You must also set MagNet's default unit length based on the value of `default_length`

2021-03-20 01:29 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
> +    def close(self, filepath = None):
The MATLAB implementation is not taking in a filepath (that is, it does not save upon closing a document). Please coordinate with @ngadiyar93 to make your implementations consistent.

2021-03-20 01:29 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
> +        centre_y = eval(self.default_length)(centrexy[1])
Let's use american style spelling:

`centre_x` should be `center_x`
`centrexy` should be `center_xy`

2021-03-20 01:29 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
> +        inner_coord_x = eval(self.default_length)(inner_coord[0])
This function should have `csToken` as its argument, not `inner_coord`.

`inner_coord` should be a field of `csToken`. Please make this consistent with the MATLAB implementation.

2021-03-20 01:29 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
>          )
The function should also return an integer that is used in resulting token. I know that MagNet doesn't need that for its sake, but other tools do. 

If needed, please review the flow of information in MATLAB. I remember typing it up as a comment in a review on one of your previous PRs

2021-03-20 01:29 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
> +    def set_default_length(self, user_unit, make_app_default):
See the comment I just gave to @ngadiyar93 on PR #186 . Let's update this function so that `user_unit` takes in eMach vocabulary (`DimMillimeter`, `DimInch`, etc.)

Also see my comment to @ngadiyar93 about adding a `set_default_angular` function

2021-03-26 14:33 UTC, Bharat-Ramadas commented on python/emach/tools/magnet/magnet.py
> +        self.default_angle = 'DimDegree'
This has been corrected

2021-03-26 14:34 UTC, Bharat-Ramadas commented on python/emach/tools/magnet/magnet.py
> +    def set_default_length(self, user_unit, make_app_default):
The Matlab implementation has been replicated in the latest commit

2021-04-04 17:56 UTC, Bharat-Ramadas commented on python/emach/tools/magnet/magnet.py
>          self.sol = self.doc.getSolution()
This does not cause an error even if the document does not have a solution.

2021-04-07 04:47 UTC, ASHAD1 commented on python/emach/tools/magnet/magnet.py
> +        self.set_default_length(length_unit, False)
Are you setting the default angle like what you have for length(`set_default_length`)? I am not sure about this in MagNet. I see that you have the property `default_angle`.

2021-04-07 04:47 UTC, ASHAD1 commented on python/emach/tools/magnet/magnet.py
> +    def open(self, filename=None, length_unit = 'DimMillimeter', angle_unit = 'DimDegree'):
Do we need to specify the length and angle unit here? I see that you are using `DimMillimeter` and `DimDegree` as your default length and angle. I think its better to specify the default unit in `_init` (`default_length` and `default_angle`) itself. This will make the `open()` signature similar to Matlab implementation.

2021-04-10 00:58 UTC, elsevers requested changes
@Bharat-Ramadas, nice job. One very minor request on a function argument name. Revise this and I will approve.

2021-04-10 00:58 UTC, elsevers commented on python/emach/tools/magnet/magnet.py
>      def draw_arc(self, centrexy, startxy, endxy):
rename `centrexy` to be `centerxy`

2021-04-10 06:22 UTC, Bharat-Ramadas commented on python/emach/tools/magnet/magnet.py
>      def draw_arc(self, centrexy, startxy, endxy):
Done!

2021-04-10 13:32 UTC, elsevers approved these changes
Looks good.

2021-04-10 20:04 UTC, aimthiazz approved these changes

2021-04-10 21:09 UTC, ASHAD1 approved these changes

2021-04-10 21:10 UTC, merged