Update MagNet MATLAB tool
Severson-Group/eMach-matlab pull request #186
Opened 2021-03-10 14:26 UTC by ngadiyar93

This PR is does the following:

1. Update MATLAB MagNet tool to separate responsibility between `open ( )` and the constructor function. 
   a. The constructor creates a MagNet instance and sets its visibility.
   b. The `open( )` function only opens a MagNet document.
   
2. Implement `save ( )` function to save the drawn / solved MagNet model. Ideally before closing, but can be used at any point.

3. Implement `close ( )` function to close the MagNet document

4. Implement the destructor function  `delete ( )` function to close the MagNet instance and destroy the object.
   
5. Update `exampleParallelogram` to demonstrate the workflow.

6. Ignore files with extensions `.mn` - These are MagNet FEA files that we typically do not want in the repo.

The workflow is as follows:
`constructor` -- > `open( )` --> (Use plumbing / porcelain functions) --> `save( )` -- > `close( )` --> `delete( )`  

Updates:
1. This PR also updates the  `ToolBase` by adding `save`, `saveAs`, and additional arguments to `open`

2. Examples have been updated to use the new function signatures.

2021-03-10 18:59 UTC, Bharat-Ramadas submitted a review, later dismissed
Modified example works

2021-03-11 04:39 UTC, Bharat-Ramadas reviewed
It just occurred to me that `visible` should not be a `protected` property. Users should be able to change visible whenever they wish to do so

2021-03-11 05:24 UTC, ngadiyar93 commented
> It just occurred to me that `visible` should not be a `protected` property. Users should be able to change visible whenever they wish to do so

@Bharat-Ramadas Users can update visibility using `setVisibility( );` I just verified that this works. So there should not be an issue.

2021-03-11 20:31 UTC, ASHAD1 commented on tools/magnet/MagNet.m
> +           % CLOSE Closes the MagNet document
Here `close()` closes the document. Do we need to specify which document to close; should we pass `fileName` as an argument for the close function like we pass in the `open()` function?

2021-03-11 21:16 UTC, elsevers requested changes

2021-03-11 21:16 UTC, elsevers commented on tools/magnet/MagNet.m
> +         function open(obj, fileName)
Change function so that the only path to creating a new document is to not have the filename argument populated. (So, don't support the `filename = 0` argument)

2021-03-11 21:16 UTC, elsevers commented on tools/magnet/MagNet.m
> +         function save(obj, path, fileName)
Need to add this function to the abstract base class `ToolBase`

2021-03-11 21:16 UTC, elsevers commented on tools/magnet/MagNet.m
> +         function open(obj, fileName)
`ToolBase` abstract base class needs to have the correct function signature

Question: do we need to specify each viable function signature in `ToolBase`?

2021-03-11 21:16 UTC, elsevers commented on tools/magnet/MagNet.m
> +           % CLOSE Closes the MagNet document
Let's have a policy that we do not open multiple documents with the same eMach tool object.

2021-03-20 01:28 UTC, elsevers requested changes
We still have a few issues with units here. I know that I previously said it is okay for `setDefaultLengthUnit` to take in a unit in MagNet language vocabulary (`millimeters`, `inches`, etc.), but I no longer think this makes sense.

https://github.com/Severson-Group/eMach/blob/e2d5828317a64945588afdda46dd9e86ed4c91a2/tools/magnet/MagNet.m#L168-L197

Instead, this function should take in units in `eMach` vocabulary and then set `MagNet` to the appropriate unit. For example, the uses passes in `userUnit = 'DimMillimeter'` and then this function calls `invoke(obj.doc, 'setDefaultLengthUnit', 'millimeters', makeAppDefault); `

If you do this, then you should use this function at the end of your constructor to get MagNet using the correct units that match your `defaultLength` and `defaultAngle`.

Note that this means that you also need to add a function `setDefaultAngularUnit` (or does MagNet only support degrees?)

2021-03-20 01:28 UTC, elsevers commented on tools/magnet/MagNet.m
> +        defaultVisibility = 0;% Default visibility
This property name of `defaultVisibility` doesn't make sense now that we have revised the class `open` and `close` methods. Let's rename it to just be `visible`. Please also update the function `setVisibility` to update this variable.

2021-03-20 01:28 UTC, elsevers commented on tools/magnet/MagNet.m
> +            set(obj.mn, 'Visible', obj.defaultVisibility);
See comment above about `visible`

2021-03-20 01:28 UTC, elsevers commented on tools/magnet/MagNet.m
>              obj.setDefaultLengthUnit('millimeters', false);
```matlab
obj.setDefaultLengthUnit('millimeters', false);
```

This needs to be set based on the value of `defaultLength`

2021-03-20 01:28 UTC, elsevers commented on tools/magnet/MagNet.m
> +         function save(obj, path, fileName)
This function is behaving as a `saveAs` function -- that is, it is taking in a file name that should be written out. Seems like we should also support a `save` function, where MagNet already knows the path it should save to. Does `MagNet` have such a function in its API? Or would we need to be tracking the file path in our tool class from the last save?

2021-03-22 03:59 UTC, ngadiyar93 commented
> We still have a few issues with units here. I know that I previously said it is okay for `setDefaultLengthUnit` to take in a unit in MagNet language vocabulary (`millimeters`, `inches`, etc.), but I no longer think this makes sense.
> 
> https://github.com/Severson-Group/eMach/blob/e2d5828317a64945588afdda46dd9e86ed4c91a2/tools/magnet/MagNet.m#L168-L197
> 
> Instead, this function should take in units in `eMach` vocabulary and then set `MagNet` to the appropriate unit. For example, the uses passes in `userUnit = 'DimMillimeter'` and then this function calls `invoke(obj.doc, 'setDefaultLengthUnit', 'millimeters', makeAppDefault); `
> 
> If you do this, then you should use this function at the end of your constructor to get MagNet using the correct units that match your `defaultLength` and `defaultAngle`.
> 
> Note that this means that you also need to add a function `setDefaultAngularUnit` (or does MagNet only support degrees?)

@elsevers I have made this update to `setDefaultLength`. 
Yes, MagNet only supports degrees for angles. It does not support radians....so there is no function to set default angular unit in MagNet.

2021-03-22 04:03 UTC, ngadiyar93 commented on tools/magnet/MagNet.m
> +         function open(obj, fileName)
@elsevers I have made the update to the `ToolBase`. I am not very sure if what I have done is exactly what is expected. Please let me know... Also, Matlab doesnt seem to require that every viable signature is specified. I checked this by opening MagNet with different number of arguments and it didnt break.

2021-03-22 04:11 UTC, ngadiyar93 commented on tools/magnet/MagNet.m
> +         function save(obj, path, fileName)
I checked this -- Magnet only has a save function that requires the filename + path to be specified. 
Even if an existing document that has already been saved earlier is re-saved in the MagNet gui by hitting `Save `(not `Save As`),  The session log still records the following:
![image](https://user-images.githubusercontent.com/43225038/111939473-66d89a00-8a9a-11eb-9ffc-3d3c6e2ccabe.png)
I think this means we need to track the path from the last save in the tool class.

2021-03-24 04:44 UTC, ASHAD1 commented on tools/ToolBase.m
> +        open(obj, fileName);
For `open()`, do we also need to specify the path of the file to open?

2021-03-24 14:36 UTC, ngadiyar93 commented on tools/ToolBase.m
> +        open(obj, fileName);
Updated to specify the path in the function signature.

2021-03-24 22:21 UTC, Bharat-Ramadas approved these changes, later dismissed
Looks good

2021-03-25 04:01 UTC, ASHAD1 approved these changes, later dismissed

2021-03-25 13:47 UTC, elsevers requested changes
Improvements look good. I have added a few requests as inline comments.

This code breaks nearly all examples and cannot be merged until this is fixed.

2021-03-25 13:47 UTC, elsevers commented on tools/ToolBase.m
> +        open(obj, path, fileName);
Why should the user have to specify both `path` and `filename`? I like the function signature you previously provided in the last round in `MagNet.m`:
`open(obj, fileName)` 

Let's go back to this.

2021-03-25 13:47 UTC, elsevers commented on tools/magnet/MagNet.m
> +         function open(obj, varargin)
1) It doesn't seem to like a good use of `varargin` if there is an optional function argument and 
2) this does not match your tool base class. 

Please use this function signature:
`open(obj, fileName)`

2021-03-25 13:47 UTC, elsevers commented on tools/ToolBase.m
> +        save(obj, path, fileName)
Again, remove `path`

2021-03-25 13:47 UTC, elsevers commented on tools/magnet/MagNet.m
> +         function save(obj, path, fileName)
Great, can you implement that?

Also, remove `path` from the function signature. Too complicated for a user.

2021-03-25 14:28 UTC, ngadiyar93 commented on tools/magnet/MagNet.m
> +         function save(obj, path, fileName)
@elsevers Question on this.
The `save` function where we track the path is only applicable if a user opens an existing file on the disk by specifying `fileName` in the `open` function. i.e, it is applicable only if the user calls `open(fileName)` by specifying an existing fileName and not simply `open( )`. 
Is that right? because I cannot how one can `save` an untitled document opened by calling `open( )` with no path specified -- it has to be a `save as` for that case.

2021-03-25 14:39 UTC, elsevers commented on tools/magnet/MagNet.m
> +         function save(obj, path, fileName)
Correct. The class needs to through an error if the objects internal filename variable has not been set.

2021-03-25 14:40 UTC, ngadiyar93 commented on tools/magnet/MagNet.m
> +         function save(obj, path, fileName)
Nevermind, i think I figured this out.

2021-03-25 22:33 UTC, elsevers requested changes
I think this is just about ready to merge. Just two small change requests.

2021-03-25 22:33 UTC, elsevers commented on tools/magnet/MagNet.m
> +            set(obj.mn, 'Visible', visible);
If we are tracking `visible` as an object property (and we are), we better update it here when this function is called.

2021-03-25 22:33 UTC, elsevers commented on tools/magnet/MagNet.m
> +            obj.fileName = fileName;
In an effort to make the code more DRY, I suggest revising this function to be:

```matlab
obj.fileName = fileName;
obj.save()
```

2021-03-25 22:46 UTC, ngadiyar93 commented
@elsevers I have addressed your change requests.

2021-03-26 00:05 UTC, elsevers approved these changes
Looks good. Thanks @ngadiyar93!

2021-03-26 00:23 UTC, Bharat-Ramadas approved these changes
Looks good

2021-03-26 00:37 UTC, merged