Add 3D Component Creation Capability
Severson-Group/eMach-matlab pull request #206
Opened 2021-04-12 18:12 UTC by Bharat-Ramadas

2021-04-14 21:59 UTC, aimthiazz submitted a review, later dismissed

2021-04-17 00:40 UTC, elsevers requested changes
Looking good. I have added detailed in line comments.

In addition to these comments, please add type-hints.

2021-04-17 00:40 UTC, elsevers commented on python/emach/model_obj/component.py
> +    def _validate_attr(self):
Need to also test the `cross_sections` list against `CrossSectBase`

2021-04-17 00:40 UTC, elsevers commented on python/emach/model_obj/location_3d.py
> +        self._anchor_xyz = anchor_xyz
Please add comments on how to interpret `anchor_xyz` and `rotate_xyz` (like are in the MATLAB code)

2021-04-17 00:40 UTC, elsevers commented on python/emach/model_obj/make_solid/make_extrude.py
> +            raise TypeError ("component depth not of type DimLinear")
Capitalize `C` in component

2021-04-17 00:40 UTC, elsevers commented on python/emach/model_obj/make_solid/make_revolve.py
> +            raise TypeError ("component angle not of type Location2D")
Capitalize `C` in component

2021-04-17 00:40 UTC, elsevers commented on python/emach/model_obj/make_solid/make_revolve.py
> +            raise TypeError ("component angle not of type Location2D")
Capitalize `C` in component

2021-04-17 00:40 UTC, elsevers commented on python/emach/model_obj/make_solid/make_revolve.py
> +            raise TypeError ("component angle not of type DimAngular")
Capitalize `C` in component

2021-04-17 00:40 UTC, elsevers commented on python/emach/model_obj/make_solid/make_solid_base.py
> +
Missing declaration of `location` property

2021-04-17 00:40 UTC, elsevers commented on python/emach/model_obj/component.py
> +class Component():
Missing clone capability in the component

2021-04-20 15:30 UTC, Bharat-Ramadas commented on python/emach/model_obj/make_solid/make_solid_base.py
> +
As Python is a dynamically typed language, we cannot "declare" properties. Instead the type of the `location` attribute is checked within `make_solid_base`

2021-04-22 16:57 UTC, elsevers requested changes

2021-04-22 16:57 UTC, elsevers commented on python/emach/model_obj/make_solid/make_solid_base.py
> +
We have been indicating properties in our other ABC's. Why wouldn't we also do that here?

The point is to communicate to a user what the expected contract should be. Please add this in the abstract base class, just like we do in the MATLAB implementation.

2021-04-22 16:57 UTC, elsevers commented on python/emach/model_obj/component.py
> +        token_make = self._make_solid.run(self._name, self._material._name, cs, maker)
It is dangerous to be using attributes that the developer intends to be hidden/protected. Please use the public facing attributes instead: 

Change `self._name` to be `self.name` 
Change `self._material._name` to be `self.material.name`

2021-04-22 16:57 UTC, elsevers commented on python/emach/model_obj/component.py
> +            raise AttributeError("name of clone same as name of original")
Please use the same error message as we have for this in the MATLAB code

2021-04-22 16:57 UTC, elsevers commented on python/emach/model_obj/make_solid/make_extrude.py
> +class MakeExtrude(MakeSolidBase):
This seems to be missing the public facing attribute `dim_depth`

2021-04-22 16:57 UTC, elsevers commented on python/emach/model_obj/make_solid/make_revolve.py
> +class MakeRevolve(MakeSolidBase):
`MakeRevolve` seems to be missing the public facing properties `dim_center`, `dim_axis`, and `dim_angle`

2021-04-22 17:25 UTC, ASHAD1 commented on python/emach/model_obj/location_3d.py
> +
Do we need to validate if the anchor_xyz and rotate_xyz are DimLinear or DimAngular?

2021-04-22 17:25 UTC, ASHAD1 commented on python/emach/model_obj/materials/material_generic.py
> +    def name(self):
This name(self) method can be defined as a property right?

2021-04-22 17:25 UTC, ASHAD1 commented on python/emach/tools/token_make.py
> +        return self._make_solid_token
Is there a reason you are not using properties for these methods cs_token(self), prep_sect_token(self), make_solid_token(self) ?

2021-05-10 18:04 UTC, Bharat-Ramadas commented on python/emach/model_obj/component.py
> +        token_make = self._make_solid.run(self._name, self._material._name, cs, maker)
The current implementation is identical to the Matlab one. Isn't it alright to change `name `within `Component `as it is a protected attribute of `Component `itself?

2021-05-26 18:47 UTC, aimthiazz approved these changes, later dismissed

2021-05-26 19:22 UTC, elsevers commented on python/emach/model_obj/component.py
> +        token_make = self._make_solid.run(self._name, self._material._name, cs, maker)
Bharat, it could be acceptable to be using `self._name`, but it is sloppy coding practice, so I would like you to revise it.

It is not acceptable to be using `self._material._name`

2021-05-26 19:26 UTC, elsevers requested changes
Please implement the changes I have previously requested.

2021-05-26 20:00 UTC, Bharat-Ramadas commented on python/emach/model_obj/component.py
> +        token_make = self._make_solid.run(self._name, self._material._name, cs, maker)
I've updated the code according to the suggested changes

2021-05-26 20:34 UTC, elsevers requested changes
See my requests in line. This is looking to be nearly ready to merge.

2021-05-26 20:34 UTC, elsevers commented on python/emach/model_obj/component.py
> +            raise AttributeError("name of clone same as name of original")
You have marked this as resolved without actually implementing my request. Please implement my request.

2021-05-26 20:34 UTC, elsevers commented on python/emach/model_obj/location_3d.py
> +        return self._rotate_xyz
Why are you placing public properties at the end of the class? Is this recommended by a Python best-practice guide? If not, I would like you to always place public properties at the beginning of the class because it makes it easier to quickly glance at the class and see them.

2021-05-26 20:34 UTC, elsevers commented on python/emach/model_obj/make_solid/make_extrude.py
> +        return self._dim_depth
Same comment as earlier about requesting that properties be defined at the start of the class

2021-05-26 20:34 UTC, elsevers commented on python/examples/example_hollow_cylinder_cross.py
> +import numpy as np
Seems like this file should now be renamed to `example_hollow_cylinder.py`. (Drop the `_cross` from the name)

2021-05-28 19:06 UTC, aimthiazz approved these changes

2021-05-28 21:12 UTC, ASHAD1 approved these changes
Looks good @Bharat-Ramadas

2021-06-08 14:26 UTC, elsevers approved these changes
Looks good.

2021-06-12 04:51 UTC, merged