Unit test documentation
Severson-Group/eMach-matlab pull request #207
Opened 2021-04-15 07:33 UTC by aimthiazz

2021-05-26 20:56 UTC, elsevers requested changes
@aimthiazz Thanks. Looking good. A few things:

You seem to have two identical markdown documents in here... I guess, delete one?

While your markdown document has the correct general content, it is not quite written from the perspective I have requested. I want this document to accomplish two things:

1. It should set our unit testing policy. You need to start by telling us that eMach unit testing for Python will use the unittest framework. Then tell us guidelines/policies, etc. 

2. It should provide some basic tutorial / how to. You have this in here, at the start of you document. This should instead be located at the end of your document, after you have declared the policy. You seem to be missing instructions on how to actually running the unit tests?

Finally, your document has several small grammar mistakes and inconsistent capitalization. Please revise.

2022-02-24 17:53 UTC, Bharat-Ramadas commented on python/emach/tests/README.md
> +This markdown document discusses the testing guidelines to be followed by the eMach contributors. The eMach testing framework is based on [unittest framework](https://docs.python.org/3/library/unitte
remove "the" from "the eMach contributrors"

2022-02-24 17:55 UTC, Bharat-Ramadas commented on python/emach/tests/README.md
> +This document assumes that the contributor is familiar with the unittest framework. However, if you are new to the unittest framework, please check out this [explainer video](https://www.youtube.com/
maybe introductory video instead of explainer video?

2022-02-24 22:44 UTC, Bharat-Ramadas reviewed
Nice work @aimthiazz !
I think the markdown has a few grammatical errors so it might be nice to review it once again before we merge it in.
In addition to this, it would be nice to have a introductory paragraph that gives the motivation for what unit testing means and why should a developer consider unit testing their code. 

Apart from these 2 points, I think the PR is ready to me merged in.

2022-02-28 05:32 UTC, Bharat-Ramadas approved these changes
Looks good!

2022-02-28 18:36 UTC, elsevers approved these changes
Looks good to me. Thanks @aimthiazz

2022-02-28 19:18 UTC, merged