Add functionality for JMAG 2D analysis
Severson-Group/eMach-matlab pull request #227
Opened 2021-11-30 20:25 UTC by Bharat-Ramadas

2021-12-01 13:58 UTC, elsevers requested changes
There seem to be a lot of "white-space only" changes in here. Are these intentional? 

If they are not, let's back out the changes. It is not a good practice to commit white space changes were inadvertently created (okay to commit them if you are doing this for a purpose, such as cleaning up a file)

2021-12-01 19:05 UTC, Bharat-Ramadas commented
The added whitespaces are intended. These changes make the files more PEP compliant (mainly [PEP 8](https://pep8.org/)) in terms of spacing and other style guidelines.

2021-12-01 21:34 UTC, elsevers commented
Can you please add a description to this PR? What functionality are you adding?

2021-12-03 06:12 UTC, aimthiazz approved these changes

2021-12-12 23:06 UTC, elsevers approved these changes

2021-12-13 02:02 UTC, merged