PM rotor
Severson-Group/eMach-matlab pull request #34
Opened 2019-02-25 19:20 UTC by ngadiyar93

2019-02-27 12:42 UTC, elsevers commented
@ngadiyar93, This branch has conflicting files that must be resolved before merging into develop.

It looks like you still need to merge develop into this branch and clean up.

2019-02-27 14:45 UTC, ngadiyar93 commented
@elsevers  In addition, I also need to update parts of the code to reflect the new parameterization. I'll complete both and indicate here when I am ready for the PR to be reviewed.

2019-03-04 14:48 UTC, ngadiyar93 commented
This PR is ready for Review

2019-03-04 19:42 UTC, elsevers commented
Drawing does not define a coherent cross-section. Please revise and let us know when you are ready to review.

2019-03-13 04:29 UTC, ngadiyar93 commented
I have updated the drawing and the code. This PR is ready for review

2019-03-13 15:56 UTC, elsevers commented
Please fix issue related to `Location2D`

2019-03-21 21:28 UTC, ngadiyar93 commented
This PR is now ready for review

2019-03-27 18:50 UTC, ngadiyar93 commented
I have merged 'develop' into PM Rotor. This fixes the issue I had with location 2D. This PR can be reviewed.

2019-04-02 13:46 UTC, elsevers requested changes
Please fix `CrossSectTrapezoid.m`

2019-04-02 13:46 UTC, elsevers commented on model_obj/crosssects/trapezoid/CrossSectTrapezoid.m
> +<<<<<<< HEAD
@ngadiyar93 It appears that you have committed a merge conflict into the your branch. Clean this up before merging.

2019-04-02 14:16 UTC, ngadiyar93 commented on model_obj/crosssects/trapezoid/CrossSectTrapezoid.m
> +<<<<<<< HEAD
@elsevers  I have resolved the merge conflict now.

2019-04-02 14:21 UTC, elsevers requested changes
Please fix `CrossSectTrapezoid.m` so that there are no changes.

2019-04-02 14:21 UTC, elsevers commented on model_obj/crosssects/trapezoid/CrossSectTrapezoid.m
> +
There is a whitespace change to this file. We should see no changes to `CrossSectTrapezoid.m` in this PR. Please fix.

2019-04-02 14:27 UTC, ngadiyar93 commented on model_obj/crosssects/trapezoid/CrossSectTrapezoid.m
> +
@elsevers  I have now fixed this.

2019-04-02 22:08 UTC, elsevers requested changes
Replace all code, folder, and file references to this being a `PMRotor` with `NotchedRotor`

Please make `InnerRotorPMRotor.pdf` more professional looking. The dimensions in particular look distorted. Please use as consistent styling with other cross-sectional drawings as possible.

2019-04-02 22:08 UTC, elsevers commented on model_obj/crosssects/inner_rotor_PMrotor/CrossSectInnerRotorPMRotor.m
> +classdef CrossSectInnerRotorPMRotor < CrossSectBase
This structure is no longer actually a PM rotor. Please remove all references to PM rotor. Replace `PMRotor` with `NotchedRotor`

2019-04-02 23:25 UTC, ngadiyar93 commented on model_obj/crosssects/inner_rotor_PMrotor/CrossSectInnerRotorPMRotor.m
> +classdef CrossSectInnerRotorPMRotor < CrossSectBase
@elsevers I have removed all references to a PM rotor and replaced 'PMRotor' with 'NotchedRotor'. I have also enhanced the figure.

2019-04-03 04:09 UTC, npetersen2 submitted a review, later dismissed
Pending Eric's approval, this seems good to me.

2019-04-03 19:11 UTC, ngadiyar93 commented
I have updated the dimension 'alpha' in the figure to be clear, using inkscape's native fonts. This PR is ready for review.

2019-04-08 18:12 UTC, elsevers approved these changes
Looks good

2019-04-08 18:12 UTC, npetersen2 approved these changes
Looks good to me!

2019-04-08 18:14 UTC, merged