XFEMM docs and tests for each problem
Severson-Group/eMach-matlab pull request #86
Opened 2019-04-01 23:27 UTC by Anvar-Khamitov

This pull request is ready for review.

2019-04-03 03:55 UTC, npetersen2 reviewed
Might want to consider adding more test cases. For example, consider arcs and segments in different quadrants to stress more `if` statements in code, i.e., make some things negative. This can tend to be problematic. Also, consider cases when arcs and lines overlap at "corner cases," like 180 degrees, etc.

2019-04-03 18:04 UTC, elsevers commented
This PR is to implement issue #80.

2019-04-03 18:09 UTC, elsevers commented
This PR also implements issue #87

2019-04-03 20:21 UTC, Anvar-Khamitov commented
This PR is ready to be merged. It solves the issue #87 . To complete the issue #80 , another PR will be created if this PR is merged.

2019-04-08 18:34 UTC, npetersen2 requested changes
Please remove extra whitespace changes.

2019-04-08 18:34 UTC, npetersen2 commented on tools/xfemm/XFEMM.m
> +
Remove this whitespace

2019-04-08 18:34 UTC, npetersen2 commented on tools/xfemm/XFEMM.m
> +
Remove this whitespace

2019-04-29 18:25 UTC, elsevers approved these changes
Looks good

2019-04-29 18:25 UTC, npetersen2 approved these changes
Looks good to me.

2019-04-29 18:25 UTC, merged