Xfemm group numbers and block labels
Severson-Group/eMach-matlab pull request #99
Opened 2019-04-29 09:59 UTC by Anvar-Khamitov

This pull request solves an issue #88.

2019-05-20 19:05 UTC, elsevers requested changes

2019-05-20 19:05 UTC, elsevers commented on model_obj/Component.m
> +            rettok = {cs, tok2};
Create a class the give a contract for the contents of `rettok`.

2019-05-20 19:05 UTC, elsevers commented on model_obj/makeSolid/MakeExtrude.m
> +            tok = {tok1, tok2};
Create a class for `tok` to guarantee the fields

2019-05-20 19:05 UTC, elsevers commented on tools/xfemm/XFEMM.m
> +            line = {seginds;0};
Create classes to compliment the XFEMM tool that specify these tokens. The class should have a couple of fields, for example:

Class: drawToken
Fields: segmentIndices, geometryType

2019-05-20 19:05 UTC, elsevers commented on tools/xfemm/XFEMM.m
> +            innerCoord = double(csToken.innerCoord);
This should return `csToken.innerCoord` without converting the units

2019-05-20 19:05 UTC, elsevers commented on tools/xfemm/XFEMM.m
> +        function tok2 = extrude(obj, name, material, depth, innerCoord)
As documented in issue #66, this needs to convert units. It does not need to be done in this PR. Can be reserved for a future PR.

2019-05-21 12:49 UTC, elsevers approved these changes
Looks good. I think this is ready to merge.

2019-05-21 12:49 UTC, elsevers commented on tools/xfemm/XFEMM.m
> +            innerCoord = double(csToken.innerCoord);
To be resolved by issue #66

2019-05-21 15:58 UTC, npetersen2 approved these changes

2019-05-21 16:19 UTC, merged